// AUTO-GENERATED by uasm - DO NOT EDIT
// Source: uasm/z8000.uasm
//
// Microcode address definitions for use in z8000_cpu.v
// Include this file to avoid hardcoded microcode addresses

`define UADDR_FETCH            12'h00C
`define UADDR_TRAP_ILLEGAL     12'h8CE
`define UADDR_TRAP_PRIV        12'h8E3
`define UADDR_TRAP_SYSCALL     12'h8F8
`define UADDR_INT_ENTRY        12'h90D
