"""Auto-generate test file from golden comparison diffs.

Takes ComparisonResult diffs and writes tests/test_z8001_golden.py containing
only the failing cases, with Z8001 golden values as expected results.
"""

from .flags import FLAG_BITS, get_flag


def generate_golden_test_file(diffs, golden, tests, output_path):
    """Write a test file containing only tests that differ from golden.

    Args:
        diffs: list of ComparisonResult from compare_golden()
        golden: dict from load_golden()
        tests: list of TestCase (the systematic tests that were run)
        output_path: path to write the generated Python file

    Returns:
        number of test cases written
    """
    # Build lookup: test_name -> TestCase
    tc_map = {tc.name: tc for tc in tests}

    # Collect failing tests
    failing = [d for d in diffs if not d.match and d.test_name in golden]

    if not failing:
        return 0

    lines = [
        '"""Auto-generated golden test cases from Z8001 reference.',
        '',
        'Generated by tests/auto_generate.py from golden comparison diffs.',
        'Each test uses Z8001-captured values as expected results.',
        '"""',
        '',
        'from .defs import TestCase',
        '',
        'TESTS = [',
    ]

    count = 0
    for comp in failing:
        name = comp.test_name
        if name not in tc_map or name not in golden:
            continue
        tc = tc_map[name]
        gdata = golden[name]

        tc_lines = _format_test_case(tc, gdata, comp)
        lines.extend(tc_lines)
        count += 1

    lines.append(']')
    lines.append('')

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    return count


def _format_test_case(tc, golden_data, comparison):
    """Format one TestCase as Python source with golden expected values.

    Returns list of source lines.
    """
    lines = []
    lines.append('    TestCase(')
    lines.append(f'        name={tc.name!r},')
    lines.append(f'        mnemonic={tc.mnemonic!r},')

    # Build description with diff summary
    diff_fields = ', '.join(d.field for d in comparison.diffs)
    desc = f'{tc.description} [diffs: {diff_fields}]'
    lines.append(f'        description={desc!r},')
    lines.append(f'        tags=["auto_generated", "z8001_validated"] + {tc.tags!r},')

    if tc.instruction:
        lines.append(f'        instruction={tc.instruction!r},')

    # Initial state
    lines.append(f'        code={tc.code!r},')
    if tc.regs:
        lines.append(f'        regs={tc.regs!r},')
    if tc.fcw != 0x4000:
        lines.append(f'        fcw=0x{tc.fcw:04X},')
    if tc.memory:
        lines.append(f'        memory={tc.memory!r},')

    # Expected results from golden
    golden_regs = {int(k): v for k, v in golden_data.get('regs', {}).items()}
    if golden_regs:
        # Only include registers that were in initial state or differ from 0
        relevant_regs = {}
        for reg, val in golden_regs.items():
            if reg in tc.regs or val != 0:
                relevant_regs[reg] = val
        if relevant_regs:
            lines.append(f'        expected_regs={relevant_regs!r},')

    # Expected flags from golden FCW
    golden_fcw = golden_data.get('fcw')
    if golden_fcw is not None:
        flags_set = []
        flags_clear = []
        for flag_name in ('C', 'Z', 'S', 'V'):
            if get_flag(golden_fcw, flag_name):
                flags_set.append(flag_name)
            else:
                flags_clear.append(flag_name)
        if flags_set:
            lines.append(f'        expected_fcw_set={flags_set!r},')
        if flags_clear:
            lines.append(f'        expected_fcw_clear={flags_clear!r},')

    # Expected memory from golden
    golden_mem = {int(k): v for k, v in golden_data.get('memory', {}).items()}
    if golden_mem:
        lines.append(f'        expected_memory={golden_mem!r},')

    # Expected exec result
    exec_result = golden_data.get('exec_result', 'HALT')
    if exec_result != 'HALT':
        lines.append(f'        expected_result={exec_result!r},')

    lines.append('    ),')
    return lines
