"""Segmented mode test generator for Z8001.

Generates TestCase objects for Z8001 segmented addressing tests.
All instruction encodings are pre-assembled with z8k-coff-as -z8001 and
verified with z8k-coff-objdump. Code words are hardcoded below with
assembler-verified listing comments.

**** IMPORTANT: NEVER hand-code Z8001 segmented values. ****
**** This includes opcodes, DA words, AND register pair values for ****
**** segmented pointers (e.g. @RRn). The encoding is NOT obvious: ****
****   segment 1, offset 0x200 in a register pair = R_even=0x8100, ****
****   R_odd=0x0200 (bit 15=1 for long-form, segment in bits 14:8). ****
**** ALWAYS use the assembler (LDA instruction) to generate segmented ****
**** pointer values in test code. See CLAUDE.md. ****
****                                                                ****
**** To re-verify encodings, assemble with:                         ****
****   z8k-coff-as -z8001 test.s -o test.o                         ****
****   z8k-coff-ld -mz8001 -T test.ld test.o -o test.elf           ****
****   z8k-coff-objdump -d test.elf                                 ****
**** using the linker script described in the section comments.     ****

Usage:
    from tests.gen_segmented import generate_segmented_tests
    tests = generate_segmented_tests()
"""

from .defs import TestCase
from .helpers import OPERAND_BASE, STACK_BASE

# Segmented FCW: System + Segmented
FCW_SEG = 0xC000

# Segment 0 short-form data address (offset < 256, in gap of bootstrap area)
SEG0_SHORT_ADDR = 0x00B4

# Segment 0 long-form data address (offset >= 256)
SEG0_LONG_ADDR = OPERAND_BASE  # 0x0400

# Segment 1 data base offset and corresponding Z80/BRAM address
SEG1_DATA_OFFSET = 0x0200
SEG1_Z80_ADDR = 0x1200  # Z80 flat address for segment 1, offset 0x0200

# Linker script used to generate the code words below:
#   OUTPUT_FORMAT("coff-z8k")
#   OUTPUT_ARCH("z8001")
#   MEMORY {
#       SEG0 : ORIGIN = 0x00000, LENGTH = 4K
#       SEG1 : ORIGIN = 0x10000, LENGTH = 4K
#   }
#   SECTIONS {
#       .text    0x00200 : { *(.text)    } > SEG0
#       .s0short 0x000B4 : { *(.s0short) } > SEG0
#       .s0long  0x00400 : { *(.s0long)  } > SEG0
#       .s0stk   0x00F00 : { *(.s0stk)   } > SEG0
#       .s1data  0x10200 : { *(.s1data)  } > SEG1
#   }


def _tc(name, mnemonic, desc, tags, code, regs=None, memory=None,
        expected_regs=None, expected_memory=None):
    """Create a segmented test case."""
    return TestCase(
        name=name,
        mnemonic=mnemonic,
        description=desc,
        tags=["systematic", "segmented"] + tags,
        target="z8001-seg",
        code=code,
        regs=regs or {},
        fcw=FCW_SEG,
        memory=memory or {},
        expected_regs=expected_regs or {},
        expected_memory=expected_memory or {},
    )


def generate_segmented_tests():
    """Generate segmented mode tests for Z8001.

    Returns a list of TestCase objects with assembler-verified instruction
    encodings for segmented DA mode. All code words were generated by
    z8k-coff-as -z8001 and verified with z8k-coff-objdump.
    """
    tests = []

    # ---- Test 1: LD R0 from segment 0, short-form DA ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0short=0xB4)
    #   200: 6100 8000 00b4    ld   r0,0xb4
    tests.append(_tc(
        name='seg_ld_r_seg0_short',
        mnemonic='LD',
        desc='LD R0, seg0:0xB4 (short-form DA)',
        tags=['segmented', 'seg0', 'short_da'],
        code=[0x6100, 0x8000, 0x00B4],
        regs={0: 0x0000},
        memory={SEG0_SHORT_ADDR: 0xBEEF},
    ))

    # ---- Test 2: ST R0 to segment 0, short-form DA ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0short=0xB4)
    #   200: 6f00 8000 00b4    ld   0xb4,r0
    tests.append(_tc(
        name='seg_st_r_seg0_short',
        mnemonic='ST',
        desc='ST R0, seg0:0xB4 (short-form DA)',
        tags=['segmented', 'seg0', 'short_da'],
        code=[0x6F00, 0x8000, 0x00B4],
        regs={0: 0xCAFE},
        memory={},
    ))
    tests[-1].expected_memory = {SEG0_SHORT_ADDR: 0xCAFE}

    # ---- Test 3: LD R0 from segment 0, long-form DA ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 6100 8000 0400    ld   r0,0x400
    tests.append(_tc(
        name='seg_ld_r_seg0_long',
        mnemonic='LD',
        desc='LD R0, seg0:0x400 (long-form DA)',
        tags=['segmented', 'seg0', 'long_da'],
        code=[0x6100, 0x8000, 0x0400],
        regs={0: 0x0000},
        memory={SEG0_LONG_ADDR: 0xDEAD},
    ))

    # ---- Test 4: ST R0 to segment 0, long-form DA ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 6f00 8000 0400    ld   0x400,r0
    tests.append(_tc(
        name='seg_st_r_seg0_long',
        mnemonic='ST',
        desc='ST R0, seg0:0x400 (long-form DA)',
        tags=['segmented', 'seg0', 'long_da'],
        code=[0x6F00, 0x8000, 0x0400],
        regs={0: 0xFACE},
        memory={},
    ))
    tests[-1].expected_memory = {SEG0_LONG_ADDR: 0xFACE}

    # ---- Test 5: LD R0 from segment 1 (cross-segment) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 6100 8100 0200    ld   r0,0x1000200
    tests.append(_tc(
        name='seg_ld_r_seg1',
        mnemonic='LD',
        desc='LD R0, seg1:0x200 (cross-segment load)',
        tags=['segmented', 'seg1', 'cross_segment'],
        code=[0x6100, 0x8100, 0x0200],
        regs={0: 0x0000},
        memory={SEG1_Z80_ADDR: 0x1234},
    ))

    # ---- Test 6: ST R0 to segment 1 (cross-segment) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 6f00 8100 0200    ld   0x1000200,r0
    tests.append(_tc(
        name='seg_st_r_seg1',
        mnemonic='ST',
        desc='ST R0, seg1:0x200 (cross-segment store)',
        tags=['segmented', 'seg1', 'cross_segment'],
        code=[0x6F00, 0x8100, 0x0200],
        regs={0: 0xABCD},
        memory={},
    ))
    tests[-1].expected_memory = {SEG1_Z80_ADDR: 0xABCD}

    # ---- Test 7: LDB RH0 from segment 1 (byte load) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 6000 8100 0200    ldb  rh0,0x1000200
    tests.append(_tc(
        name='seg_ldb_rh0_seg1',
        mnemonic='LDB',
        desc='LDB RH0, seg1:0x200 (byte load cross-segment)',
        tags=['segmented', 'seg1', 'byte', 'cross_segment'],
        code=[0x6000, 0x8100, 0x0200],
        regs={0: 0x0000},
        memory={SEG1_Z80_ADDR: 0xAB00},
    ))

    # ---- Test 8: STB RH0 to segment 1 (byte store) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 6e00 8100 0200    ldb  0x1000200,rh0
    tests.append(_tc(
        name='seg_stb_rh0_seg1',
        mnemonic='STB',
        desc='STB RH0, seg1:0x200 (byte store cross-segment)',
        tags=['segmented', 'seg1', 'byte', 'cross_segment'],
        code=[0x6E00, 0x8100, 0x0200],
        regs={0: 0xCD00},
        memory={SEG1_Z80_ADDR: 0x0000},
    ))
    tests[-1].expected_memory = {SEG1_Z80_ADDR: 0xCD00}

    # ---- Test 9: LD R0, @RR2 (indirect, segment 0) ----
    # RR2 set up by LDA in code — never hand-code segmented pointer registers
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 7602 8000 0400    lda  rr2,0x400
    #   206: 2120              ld   r0,@rr2
    tests.append(_tc(
        name='seg_ld_r_ir_seg0',
        mnemonic='LD',
        desc='LD R0, @RR2 (indirect, seg 0 offset 0x400)',
        tags=['segmented', 'seg0', 'indirect'],
        code=[0x7602, 0x8000, 0x0400, 0x2120],
        regs={0: 0x0000},
        memory={SEG0_LONG_ADDR: 0x9876},
    ))

    # ---- Test 10: LD R0, @RR2 (indirect, segment 1) ----
    # RR2 set up by LDA in code — never hand-code segmented pointer registers
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 7602 8100 0200    lda  rr2,0x1000200
    #   206: 2120              ld   r0,@rr2
    tests.append(_tc(
        name='seg_ld_r_ir_seg1',
        mnemonic='LD',
        desc='LD R0, @RR2 (indirect, seg 1 offset 0x200)',
        tags=['segmented', 'seg1', 'indirect', 'cross_segment'],
        code=[0x7602, 0x8100, 0x0200, 0x2120],
        regs={0: 0x0000},
        memory={SEG1_Z80_ADDR: 0x5432},
    ))

    # ---- Test 11: ST R0, @RR2 (indirect store, segment 1) ----
    # RR2 set up by LDA in code — never hand-code segmented pointer registers
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 7602 8100 0200    lda  rr2,0x1000200
    #   206: 2f20              ld   @rr2,r0
    tests.append(_tc(
        name='seg_st_r_ir_seg1',
        mnemonic='ST',
        desc='ST R0, @RR2 (indirect store, seg 1 offset 0x200)',
        tags=['segmented', 'seg1', 'indirect', 'cross_segment'],
        code=[0x7602, 0x8100, 0x0200, 0x2F20],
        regs={0: 0xFEDC},
        memory={},
    ))
    tests[-1].expected_memory = {SEG1_Z80_ADDR: 0xFEDC}

    # ---- Test 12: LD R0, addr(R5) segment 0 (indexed) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 6150 8000 0400    ld   r0,0x400(r5)
    tests.append(_tc(
        name='seg_ld_r_x_seg0',
        mnemonic='LD',
        desc='LD R0, seg0:0x400(R5) (indexed, R5=4)',
        tags=['segmented', 'seg0', 'indexed'],
        code=[0x6150, 0x8000, 0x0400],
        regs={0: 0x0000, 5: 0x0004},
        memory={SEG0_LONG_ADDR + 4: 0x4321},
    ))

    # ---- Test 13: LD R0, addr(R5) segment 1 (indexed, cross-segment) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 6150 8100 0200    ld   r0,0x1000200(r5)
    tests.append(_tc(
        name='seg_ld_r_x_seg1',
        mnemonic='LD',
        desc='LD R0, seg1:0x200(R5) (indexed, R5=6)',
        tags=['segmented', 'seg1', 'indexed', 'cross_segment'],
        code=[0x6150, 0x8100, 0x0200],
        regs={0: 0x0000, 5: 0x0006},
        memory={SEG1_Z80_ADDR + 6: 0x8765},
    ))

    # ---- Test 14: Segment isolation ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2100 aaaa         ld   r0,#0xaaaa
    #   204: 6f00 8000 0400    ld   0x400,r0
    #   20a: 2100 5555         ld   r0,#0x5555
    #   20e: 6f00 8100 0200    ld   0x1000200,r0
    #   214: 6101 8000 0400    ld   r1,0x400
    #   21a: 6102 8100 0200    ld   r2,0x1000200
    tests.append(_tc(
        name='seg_isolation',
        mnemonic='ST',
        desc='Write seg0:0x400=0xAAAA, seg1:0x200=0x5555, verify both',
        tags=['segmented', 'seg0', 'seg1', 'cross_segment', 'isolation'],
        code=[0x2100, 0xAAAA, 0x6F00, 0x8000, 0x0400,
              0x2100, 0x5555, 0x6F00, 0x8100, 0x0200,
              0x6101, 0x8000, 0x0400, 0x6102, 0x8100, 0x0200],
        regs={0: 0x0000, 1: 0x0000, 2: 0x0000},
        memory={SEG0_LONG_ADDR: 0x0000, SEG1_Z80_ADDR: 0x0000},
    ))
    tests[-1].expected_memory = {
        SEG0_LONG_ADDR: 0xAAAA,
        SEG1_Z80_ADDR: 0x5555,
    }

    # ---- Test 15: JP label (intra-segment) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2100 1234         ld   r0,#0x1234
    #   204: 5e08 8000 020e    jp   t,0x20e
    #   20a: 2100 dead         ld   r0,#0xdead       (skipped)
    #   20e: 2101 5678         ld   r1,#0x5678        (target)
    tests.append(_tc(
        name='seg_jp_seg0',
        mnemonic='JP',
        desc='JP target (intra-segment jump, skip one instruction)',
        tags=['segmented', 'seg0', 'branch'],
        code=[0x2100, 0x1234, 0x5E08, 0x8000, 0x020E,
              0x2100, 0xDEAD, 0x2101, 0x5678],
        regs={0: 0x0000, 1: 0x0000},
    ))

    # ---- Test 16: CALL/RET (segment 0) ----
    # RR14 stack pointer set up by LDA — never hand-code segmented pointers
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0stk=0xF00)
    #   200: 760e 8000 0f00    lda  rr14,0xf00
    #   206: 2100 0000         ld   r0,#0x0
    #   20a: 5f00 8000 021a    call 0x21a
    #   210: 2100 aaaa         ld   r0,#0xaaaa
    #   214: 5e08 8000 0220    jp   t,0x220           (done)
    #   21a: 2100 1234         ld   r0,#0x1234        (subroutine)
    #   21e: 9e08              ret
    #   220:                                          (done label)
    # CALL at 0x20A is 6 bytes (seg long-form), return address = 0x210
    # Stack residue after RET: PCSEG at SP-4, offset at SP-2
    tests.append(_tc(
        name='seg_call_ret_seg0',
        mnemonic='CALL',
        desc='CALL subroutine / RET (segmented stack)',
        tags=['segmented', 'seg0', 'call', 'ret'],
        code=[0x760E, 0x8000, 0x0F00, 0x2100, 0x0000,
              0x5F00, 0x8000, 0x021A, 0x2100, 0xAAAA,
              0x5E08, 0x8000, 0x0220, 0x2100, 0x1234, 0x9E08],
        regs={0: 0x0000},
        expected_memory={
            0x0EFC: 0x8000,  # PCSEG (segment 0, long form)
            0x0EFE: 0x0210,  # PC offset (return address after CALL)
        },
    ))

    # ---- Test 16b: CALL @RR4 (segment 0) ----
    # Based on z8000_micro/tests/asm/test_z8001_seg.s TEST 31, minimized.
    #   200: 7604 8000 0216    lda  rr4,0x216
    #   206: 2100 0000         ld   r0,#0x0
    #   20a: 1f40              call @rr4
    #   20c: 2100 aaaa         ld   r0,#0xaaaa        (return path)
    #   210: 5e08 8000 021c    jp   t,0x21c
    #   216: 2101 1234         ld   r1,#0x1234        (subroutine)
    #   21a: 9e08              ret
    tests.append(_tc(
        name='seg_call_ir_ret_seg0',
        mnemonic='CALL',
        desc='CALL @RR4; RET (segmented indirect call/return)',
        tags=['segmented', 'seg0', 'call', 'ret', 'IR_mode'],
        code=[0x7604, 0x8000, 0x0216, 0x2100, 0x0000, 0x1F40,
              0x2100, 0xAAAA, 0x5E08, 0x8000, 0x021C,
              0x2101, 0x1234, 0x9E08],
        regs={0: 0x0000, 1: 0x0000},
        expected_regs={0: 0xAAAA, 1: 0x1234},
    ))

    # ---- Test 16c: CALL address(R5) (segment 0) ----
    #   200: 2105 0018         ld   r5,#0x18
    #   204: 2100 0000         ld   r0,#0x0
    #   208: 5f50 8000 0200    call 0x200(r5)
    #   20e: 2100 aaaa         ld   r0,#0xaaaa        (return path)
    #   212: 5e08 8000 021e    jp   t,0x21e
    #   218: 2101 5678         ld   r1,#0x5678        (subroutine)
    #   21c: 9e08              ret
    tests.append(_tc(
        name='seg_call_x_ret_seg0',
        mnemonic='CALL',
        desc='CALL 0x0200(R5); RET (segmented indexed call/return)',
        tags=['segmented', 'seg0', 'call', 'ret', 'X_mode'],
        code=[0x2105, 0x0018, 0x2100, 0x0000, 0x5F50, 0x8000, 0x0200,
              0x2100, 0xAAAA, 0x5E08, 0x8000, 0x021E,
              0x2101, 0x5678, 0x9E08],
        regs={0: 0x0000, 1: 0x0000, 5: 0x0000},
        expected_regs={0: 0xAAAA, 1: 0x5678},
    ))

    # ---- Test 17: PUSH/POP @RR14 (segmented stack) ----
    # RR14 stack pointer set up by LDA — never hand-code segmented pointers
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0stk=0xF00)
    #   200: 760e 8000 0f00    lda  rr14,0xf00
    #   206: 2100 beef         ld   r0,#0xbeef
    #   20a: 93e0              push @rr14,r0
    #   20c: 2100 0000         ld   r0,#0x0
    #   210: 97e0              pop  r0,@rr14
    tests.append(_tc(
        name='seg_push_pop_seg0',
        mnemonic='PUSH',
        desc='PUSH @RR14, R0 / POP R0, @RR14 (segmented stack)',
        tags=['segmented', 'seg0', 'push', 'pop', 'stack'],
        code=[0x760E, 0x8000, 0x0F00, 0x2100, 0xBEEF,
              0x93E0, 0x2100, 0x0000, 0x97E0],
        regs={0: 0x0000},
    ))

    # ---- Test 17b: PUSHL @RR4, RR6 (long push via segmented register-PAIR pointer) ----
    # Mirrors PCOS calluser.s `pushl @rr4, rr6`: the stack pointer is an arbitrary
    # register pair (not RR14/RR15) and the pushed value is a 32-bit seg:offset.
    # RR4 = seg0:0xF00 (pointer), RR6 = seg0:0x430 (value). PUSHL predecrements RR4
    # by 4 then stores RR6 at the new RR4. Observe the two pushed words.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7604 8000 0f00    lda   rr4,0xf00
    #   206: 7606 8000 0430    lda   rr6,0x430
    #   20c: 9146              pushl @rr4,rr6
    tests.append(_tc(
        name='seg_pushl_ir_rr_seg0',
        mnemonic='PUSHL',
        desc='PUSHL @RR4, RR6 (long push via segmented register-pair pointer)',
        tags=['segmented', 'seg0', 'pushl', 'stack', 'ir_pair'],
        code=[0x7604, 0x8000, 0x0F00,
              0x7606, 0x8000, 0x0430,
              0x9146],
        regs={4: 0x0000, 5: 0x0000, 6: 0x0000, 7: 0x0000},
    ))
    tests[-1].observe_memory = [0x0EFC, 0x0EFE]

    # ---- Test 17c: PUSHL then POPL round-trip via segmented register-PAIR pointer ----
    # Exercises both PUSHL @RR4,RR6 and POPL RR8,@RR4. After the round-trip RR8
    # should equal RR6 and RR4 should return to seg0:0xF00.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7604 8000 0f00    lda   rr4,0xf00
    #   206: 7606 8000 0430    lda   rr6,0x430
    #   20c: 9146              pushl @rr4,rr6
    #   20e: 9548              popl  rr8,@rr4
    tests.append(_tc(
        name='seg_pushl_popl_ir_rr_seg0',
        mnemonic='PUSHL',
        desc='PUSHL @RR4,RR6 then POPL RR8,@RR4 (segmented pair pointer round-trip)',
        tags=['segmented', 'seg0', 'pushl', 'popl', 'stack', 'ir_pair'],
        code=[0x7604, 0x8000, 0x0F00,
              0x7606, 0x8000, 0x0430,
              0x9146, 0x9548],
        regs={4: 0x0000, 5: 0x0000, 6: 0x0000, 7: 0x0000,
              8: 0x0000, 9: 0x0000},
    ))
    tests[-1].observe_memory = [0x0EFC, 0x0EFE]

    # ---- Test 17d: LD word via BX (segmented register-PAIR base + index) ----
    # Mirrors PCOS reloc_type4_word `ld rr2(r7), r6` (STORE) / `ld r6, rr2(r7)`.
    # Base RR2 = seg0:0x400, index R7 = 0x10 -> effective offset 0x410. Store R6
    # (0xBEEF) there, then load it back into R8. NOTE: the segmented assembler
    # requires a register-PAIR base here; the existing seg_cov_161/166 BX tests use
    # a word-register base (-z8002 encoding) and do NOT exercise this form.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7602 8000 0400    lda  rr2,0x400
    #   206: 2107 0010         ld   r7,#0x10
    #   20a: 2106 beef         ld   r6,#0xbeef
    #   20e: 7326 0700         ld   rr2(r7),r6
    #   212: 7128 0700         ld   r8,rr2(r7)
    tests.append(_tc(
        name='seg_ld_bx_store_rr_seg0',
        mnemonic='LD',
        desc='LD rr2(r7),r6 then LD r8,rr2(r7) (segmented pair-base indexed word store/load)',
        tags=['segmented', 'seg0', 'ld', 'bx_pair', 'indexed', 'store'],
        code=[0x7602, 0x8000, 0x0400,
              0x2107, 0x0010,
              0x2106, 0xBEEF,
              0x7326, 0x0700,
              0x7128, 0x0700],
        regs={2: 0x0000, 3: 0x0000, 6: 0x0000, 7: 0x0000, 8: 0x0000},
        memory={SEG0_LONG_ADDR + 0x10: 0x0000},
    ))
    tests[-1].observe_memory = [SEG0_LONG_ADDR + 0x10]

    # ---- Test 17e: LDB byte via BX (segmented register-PAIR base + index) ----
    # Mirrors PCOS reloc_type5_seg `ldb rr2(r7), rh6` (STORE) / `ldb rh6, rr2(r7)`.
    # Base RR2 = seg0:0x400, index R7 = 0x11 (odd lane) -> offset 0x411. Store byte
    # 0xA5 there, then load it back into RH0. mem[0x410] is preloaded so the
    # unaffected (high) byte is observable.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7602 8000 0400    lda  rr2,0x400
    #   206: 2107 0011         ld   r7,#0x11
    #   20a: c6a5              ldb  rh6,#0xa5
    #   20c: 7226 0700         ldb  rr2(r7),rh6
    #   210: 7020 0700         ldb  rh0,rr2(r7)
    tests.append(_tc(
        name='seg_ldb_bx_store_rr_seg0',
        mnemonic='LDB',
        desc='LDB rr2(r7),rh6 then LDB rh0,rr2(r7) (segmented pair-base indexed byte store/load)',
        tags=['segmented', 'seg0', 'ldb', 'bx_pair', 'indexed', 'store', 'byte'],
        code=[0x7602, 0x8000, 0x0400,
              0x2107, 0x0011,
              0xC6A5,
              0x7226, 0x0700,
              0x7020, 0x0700],
        regs={0: 0x0000, 2: 0x0000, 3: 0x0000, 6: 0x0000, 7: 0x0000},
        memory={SEG0_LONG_ADDR + 0x10: 0x1234},
    ))
    tests[-1].observe_memory = [SEG0_LONG_ADDR + 0x10]

    # ---- Test 17f: LDL via BA (segmented register-PAIR base + immediate disp) ----
    # Mirrors PCOS `ldl rr10, rr2(#4)` (opcode 0x35, LDL base+disp). Base RR2 =
    # seg0:0x400, disp #4 -> load the 32-bit value at seg0:0x404 into RR10.
    # NOTE: seg_cov_218 also covers the generated BA form. Keep this targeted
    # test as a stronger segmented-pair check with a known 32-bit value.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7602 8000 0400    lda  rr2,0x400
    #   206: 352a 0004         ldl  rr10,rr2(#0x4)
    tests.append(_tc(
        name='seg_ldl_ba_rr_seg0',
        mnemonic='LDL',
        desc='LDL RR10, RR2(#4) (segmented pair-base + immediate displacement)',
        tags=['segmented', 'seg0', 'ldl', 'ba_pair', 'based'],
        code=[0x7602, 0x8000, 0x0400,
              0x352A, 0x0004],
        regs={2: 0x0000, 3: 0x0000, 10: 0x0000, 11: 0x0000},
        memory={SEG0_LONG_ADDR + 4: 0x1234, SEG0_LONG_ADDR + 6: 0x5678},
    ))

    # ---- Test 17g: LDA via BA (segmented register-PAIR base + immediate disp) ----
    # `lda rr8, rr2(#4)` (opcode 0x34, LDA base+disp). Base RR2 = seg0:0x400,
    # disp #4 -> RR8 receives the effective segmented address seg0:0x404 (no
    # memory read). dest(RR8) != base(RR2). NOTE: seg_cov_173 also covers the
    # generated BA form. Keep this targeted test as a stronger segmented-pair check.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7602 8000 0400    lda  rr2,0x400
    #   206: 3428 0004         lda  rr8,rr2(#0x4)
    tests.append(_tc(
        name='seg_lda_ba_rr_seg0',
        mnemonic='LDA',
        desc='LDA RR8, RR2(#4) (segmented pair-base + immediate displacement)',
        tags=['segmented', 'seg0', 'lda', 'ba_pair', 'based'],
        code=[0x7602, 0x8000, 0x0400,
              0x3428, 0x0004],
        regs={2: 0x0000, 3: 0x0000, 8: 0x0000, 9: 0x0000},
    ))

    # ---- Test 17h: LDA BA cross-segment (catches stale-segment hazard) ----
    # `lda rr8, rr4(#4)` must take its SEGMENT from the base RR4, not from
    # whatever segment was last touched. Prime a different segment first with a
    # seg1 indirect read, then LDA a seg0 base: the result must be seg0:0x404.
    #   RR2 = seg1:0x200 (preset), RR4 = seg0:0x400 (preset)
    #   ld  r0,@rr2       -> reads seg1:0x200 (0xCAFE), sets the data segment to 1
    #   lda rr8,rr4(#4)   -> RR8 = seg0:0x404   (NOT seg1:0x404)
    # A soft core that carries the previous segment into the LDA result yields
    # 8100:0404 here instead of 8000:0404; the hard-CPU golden is 8000:0404.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2120              ld   r0,@rr2
    #   202: 3448 0004         lda  rr8,rr4(#0x4)
    tests.append(_tc(
        name='seg_lda_ba_xseg',
        mnemonic='LDA',
        desc='LDA RR8, RR4(#4) after a seg1 read (segment must come from base, not prior access)',
        tags=['segmented', 'cross_segment', 'lda', 'ba_pair', 'based'],
        code=[0x2120,
              0x3448, 0x0004],
        regs={0: 0x0000,
              2: 0x8100, 3: 0x0200,   # RR2 = seg1:0x200
              4: 0x8000, 5: 0x0400,   # RR4 = seg0:0x400
              8: 0x0000, 9: 0x0000},
        memory={SEG1_Z80_ADDR: 0xCAFE},
    ))

    # ---- Test 17i: LDCTL PSAPOFF reserved-low-byte round-trip ----
    # Resolves whether the real Z8001 preserves the reserved low byte of PSAPOFF.
    # Per z8000.md the load takes only PSAPOFF(8:15) and the readback leaves
    # Rd(0:7) UNDEFINED, so the low byte is architecturally undefined -- but the
    # hard-CPU golden reveals the chip's ACTUAL behavior (what the BIOS observes):
    #   R2 = 0x08FF -> chip preserves & returns the low byte (soft core must keep it)
    #   R2 = 0x08xx (low != FF, e.g. 0x0800) -> chip drops it (masking is fine)
    # R1 stays 0x08FF (the written value) as a control.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 08ff         ld    r1,#0x8ff
    #   204: 7d1d              ldctl psapoff,r1
    #   206: 2102 0000         ld    r2,#0x0
    #   20a: 7d25              ldctl r2,psapoff
    tests.append(_tc(
        name='seg_ldctl_psapoff_lowbyte',
        mnemonic='LDCTL',
        desc='LDCTL PSAPOFF,R1(0x08FF) then LDCTL R2,PSAPOFF (reserved low-byte round-trip)',
        tags=['segmented', 'control', 'ldctl', 'psap', 'reserved_low_byte'],
        code=[0x2101, 0x08FF,
              0x7D1D,
              0x2102, 0x0000,
              0x7D25],
        regs={1: 0x0000, 2: 0x0000},
    ))

    # ---- Test 18: LDL RR0 from segment 1 (32-bit load) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 5400 8100 0200    ldl  rr0,0x1000200
    tests.append(_tc(
        name='seg_ldl_rr0_seg1',
        mnemonic='LDL',
        desc='LDL RR0, seg1:0x200 (32-bit load cross-segment)',
        tags=['segmented', 'seg1', 'long_word', 'cross_segment'],
        code=[0x5400, 0x8100, 0x0200],
        regs={0: 0x0000, 1: 0x0000},
        memory={SEG1_Z80_ADDR: 0x1234, SEG1_Z80_ADDR + 2: 0x5678},
    ))

    # ---- Test 19: LDA RR2, seg0_data (load address) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 7602 8000 0400    lda  rr2,0x400
    tests.append(_tc(
        name='seg_lda_rr2_seg0',
        mnemonic='LDA',
        desc='LDA RR2, seg0:0x400 (load segmented address)',
        tags=['segmented', 'seg0', 'load_address'],
        code=[0x7602, 0x8000, 0x0400],
        regs={2: 0x0000, 3: 0x0000},
    ))

    # ---- Test 20: ADD R0, seg0_da (arithmetic with DA mode) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 4100 8000 0400    add  r0,0x400
    tests.append(_tc(
        name='seg_add_r_da_seg0',
        mnemonic='ADD',
        desc='ADD R0, seg0:0x400 (arithmetic with DA addressing)',
        tags=['segmented', 'seg0', 'arithmetic', 'da_mode'],
        code=[0x4100, 0x8000, 0x0400],
        regs={0: 0x1000},
        memory={SEG0_LONG_ADDR: 0x0234},
    ))

    # ---- Test 21: IRET (segmented) ----
    # Stack frame consumed by IRET: identifier, FCW, PCSEG, PC offset.
    #   200: 7b00                iret
    #   202: 2100 dead           ld   r0,#0xdead     (failure path)
    #   206: 5e08 8000 00c0      jp   t,0xc0
    #   20c: 2100 55aa           ld   r0,#0x55aa     (return target)
    tests.append(_tc(
        name='seg_iret_basic',
        mnemonic='IRET',
        desc='IRET: restore FCW/PCSEG/PC from segmented system stack',
        tags=['segmented', 'control', 'iret', 'stack'],
        code=[0x7B00, 0x2100, 0xDEAD, 0x5E08, 0x8000, 0x00C0,
              0x2100, 0x55AA],
        regs={0: 0x0000, 14: 0x8000, 15: STACK_BASE},
        memory={
            STACK_BASE: 0x0000,          # Identifier/reserved word
            STACK_BASE + 2: FCW_SEG,     # Restored FCW
            STACK_BASE + 4: 0x8000,      # Return PCSEG: segment 0
            STACK_BASE + 6: 0x020C,      # Return PC offset: success label
        },
        expected_regs={0: 0x55AA, 14: 0x8000, 15: STACK_BASE + 8},
    ))

    # ---- Test 22: LDPS @RRs (segmented) ----
    # Segmented PS block: reserved, FCW, PCSEG, PC offset.
    # Based on z8000_micro/tests/asm/test_z8001_seg.s LDPS @RR4 pattern.
    #   200: 3940                ldps @rr4
    #   202: 2100 dead           ld   r0,#0xdead     (failure path)
    #   206: 5e08 8000 00c0      jp   t,0xc0
    #   20c: 2100 55aa           ld   r0,#0x55aa     (return target)
    tests.append(_tc(
        name='seg_ldps_ir_basic',
        mnemonic='LDPS',
        desc='LDPS @RR4: load FCW/PCSEG/PC from segmented program status block',
        tags=['segmented', 'control', 'ldps', 'IR_mode'],
        code=[0x3940, 0x2100, 0xDEAD, 0x5E08, 0x8000, 0x00C0,
              0x2100, 0x55AA],
        regs={0: 0x0000, 4: 0x8000, 5: SEG0_LONG_ADDR},
        memory={
            SEG0_LONG_ADDR: 0x0000,
            SEG0_LONG_ADDR + 2: FCW_SEG,
            SEG0_LONG_ADDR + 4: 0x8000,
            SEG0_LONG_ADDR + 6: 0x020C,
        },
        expected_regs={0: 0x55AA},
    ))

    # ---- Test 23: LDPS DA (segmented) ----
    #   200: 7900 8000 0400      ldps 0x400
    #   206: 2100 dead           ld   r0,#0xdead     (failure path)
    #   20a: 5e08 8000 00c0      jp   t,0xc0
    #   210: 2100 55aa           ld   r0,#0x55aa     (return target)
    tests.append(_tc(
        name='seg_ldps_da_basic',
        mnemonic='LDPS',
        desc='LDPS seg0:0x400: load FCW/PCSEG/PC from direct program status block',
        tags=['segmented', 'control', 'ldps', 'DA_mode'],
        code=[0x7900, 0x8000, SEG0_LONG_ADDR, 0x2100, 0xDEAD,
              0x5E08, 0x8000, 0x00C0, 0x2100, 0x55AA],
        regs={0: 0x0000},
        memory={
            SEG0_LONG_ADDR: 0x0000,
            SEG0_LONG_ADDR + 2: FCW_SEG,
            SEG0_LONG_ADDR + 4: 0x8000,
            SEG0_LONG_ADDR + 6: 0x0210,
        },
        expected_regs={0: 0x55AA},
    ))

    # ---- Test 24: LDPS X (segmented) ----
    #   200: 7930 8000 0400      ldps 0x400(r3)
    #   206: 2100 dead           ld   r0,#0xdead     (failure path)
    #   20a: 5e08 8000 00c0      jp   t,0xc0
    #   210: 2100 55aa           ld   r0,#0x55aa     (return target)
    tests.append(_tc(
        name='seg_ldps_x_basic',
        mnemonic='LDPS',
        desc='LDPS seg0:0x400(R3): load FCW/PCSEG/PC from indexed program status block',
        tags=['segmented', 'control', 'ldps', 'X_mode'],
        code=[0x7930, 0x8000, SEG0_LONG_ADDR, 0x2100, 0xDEAD,
              0x5E08, 0x8000, 0x00C0, 0x2100, 0x55AA],
        regs={0: 0x0000, 3: 0x0008},
        memory={
            SEG0_LONG_ADDR + 8: 0x0000,
            SEG0_LONG_ADDR + 10: FCW_SEG,
            SEG0_LONG_ADDR + 12: 0x8000,
            SEG0_LONG_ADDR + 14: 0x0210,
        },
        expected_regs={0: 0x55AA},
    ))

    # ---- Test 25: SC #0 (System Call trap, segmented) ----
    # Sets up PSAP and system stack, executes SC, handler loads R0 marker.
    # Stack frame (4 words pushed): identifier, old FCW, PCSEG, PC offset
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0x0f00
    #   212: 2100 0000           ld   r0,#0x0
    #   216: 7f00                sc   #0
    #   218: 2100 dead           ld   r0,#0xdead          (should NOT execute)
    #   21c: 5e08 00c0           jp   t,0x00c0            (should NOT reach)
    # Handler at 0x300 (via memory preload):
    #   300: 2100 55aa           ld   r0,#0x55aa
    #   304: 5e08 00c0           jp   t,0x00c0
    # PSA at PSAP+0x18=0x818: reserved(+0), FCW(+2), PCSEG(+4), PC_off(+6)
    tests.append(_tc(
        name='seg_sc_basic',
        mnemonic='SC',
        desc='SC #0: system call trap, verify stack frame',
        tags=['segmented', 'seg0', 'sc', 'trap'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x2100, 0x0000, 0x7F00,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000},
        memory={
            # Handler code at 0x300
            0x0300: 0x2100, 0x0302: 0x55AA,
            0x0304: 0x5E08, 0x0306: 0x00C0,
            # PSA: reserved(+0), FCW(+2), PCSEG(+4), PC_off(+6)
            0x0818: 0x0000, 0x081A: 0xC000,
            0x081C: 0x8000, 0x081E: 0x0300,
        },
        expected_regs={0: 0x55AA, 14: 0x8000, 15: 0x0EF8},
        expected_memory={
            0x0EF8: 0x7F00,  # Identifier (SC instruction word)
            0x0EFA: 0xC000,  # Old FCW
            0x0EFC: 0x8000,  # PCSEG (segment 0, long form)
            0x0EFE: 0x0218,  # PC offset (return address after SC)
        },
    ))

    # ---- Tests 26/27: which PSA entry does each internal trap use? ----
    # Both tests install the SAME two program status blocks and differ only in
    # the instruction that traps, so the marker left in R0 names the entry the
    # part vectored through.  No trace reading required.
    #
    #   PSAP+0x08  (0x808)  -> handler at 0x300, R0 = 0xE0E0
    #   PSAP+0x10  (0x810)  -> handler at 0x320, R0 = 0xB0B0
    #
    # z8000.md Figure 7-2 (Z8001/Z8003) gives 0x08 = EXTENDED INSTRUCTION TRAP
    # and 0x10 = PRIVILEGED INSTRUCTION TRAP, so the manual predicts 0xE0E0 for
    # ext8e and 0xB0B0 for MSET.  Filling both blocks means a wrong vector
    # lands on the other handler instead of on zeros, and 0xDEAD still means
    # no trap at all - the three outcomes are distinguishable.
    #
    # The PSA blocks also carry the trace evidence for which address space the
    # fetch uses; seg_sc_basic already pinned that as data space for SC.
    PSA_BOTH = {
        # handler A - reached via PSAP+0x08
        0x0300: 0x2100, 0x0302: 0xE0E0, 0x0304: 0x5E08, 0x0306: 0x00C0,
        # handler B - reached via PSAP+0x10
        0x0320: 0x2100, 0x0322: 0xB0B0, 0x0324: 0x5E08, 0x0326: 0x00C0,
        # PSA block at PSAP+0x08: reserved, FCW, PCSEG, PC offset
        0x0808: 0x0000, 0x080A: 0xC000, 0x080C: 0x8000, 0x080E: 0x0300,
        # PSA block at PSAP+0x10
        0x0810: 0x0000, 0x0812: 0xC000, 0x0814: 0x8000, 0x0816: 0x0320,
    }

    # ---- Test 26: extended-instruction trap ----
    # ext8e with EPA clear traps rather than handing the instruction to an EPU.
    # Executed in system mode, so privilege is not in question.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0xf00
    #   212: 2100 0000           ld   r0,#0x0
    #   216: 8e11                ext8e #0x11
    #   218: 2100 dead           ld   r0,#0xdead          (only if no trap)
    #   21c: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_epu_trap',
        mnemonic='EXT8E',
        desc='ext8e with EPA clear: which PSA entry does the extended-instruction trap use?',
        tags=['segmented', 'seg0', 'trap', 'epu', 'psa'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x2100, 0x0000, 0x8E11,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000},
        memory=dict(PSA_BOTH),
        # manual: R0=0xE0E0 (via PSAP+0x08)
    ))

    # ---- Test 27: privileged-instruction trap ----
    # LDCTL FCW drops S/N to enter normal mode, where DI - listed among the
    # privileged instructions in z8000.md 6.2 - traps.  The handler runs in
    # system mode from the PSA FCW, so the dump routine still works.
    #
    # DI rather than MSET: MSET is privileged too, but on the part it vectors
    # through PSAP+0x08 instead of PSAP+0x10, so it does not represent the
    # class.  DI, IRET and LDCTL all agree on PSAP+0x10.  seg_mset_trap below
    # keeps the odd case.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0xf00
    #   212: 2100 0000           ld   r0,#0x0
    #   216: 2101 8000           ld   r1,#0x8000
    #   21a: 7d1a                ldctl fcw,r1             (normal mode)
    #   21c: 7c00                di   vi,nvi              (privileged -> trap)
    #   21e: 2100 dead           ld   r0,#0xdead          (only if no trap)
    #   222: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_priv_trap',
        mnemonic='DI',
        desc='DI in normal mode: which PSA entry does the privileged-instruction trap use?',
        tags=['segmented', 'seg0', 'trap', 'privileged', 'psa'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x2100, 0x0000,
              0x2101, 0x8000, 0x7D1A, 0x7C00,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000},
        memory=dict(PSA_BOTH),
        # manual: R0=0xB0B0 (via PSAP+0x10)
    ))

    # ---- Test 28: MSET is the exception ----
    # MSET is privileged (z8000.md 6.2) but does not vector like the other
    # privileged instructions: DI, IRET and LDCTL all take PSAP+0x10 while
    # MSET takes PSAP+0x08, the extended-instruction entry.  MSET drives the
    # multi-micro MI/MO pins, which this harness leaves unterminated, so the
    # part may not be reaching the privilege check at all and may be trapping
    # the opcode as unimplemented instead.  Captured so the behaviour is
    # recorded rather than mistaken for the general case.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   ... identical to seg_priv_trap through 0x21a ...
    #   21c: 7b08                mset                     (privileged -> trap)
    #   21e: 2100 dead           ld   r0,#0xdead          (only if no trap)
    #   222: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_mset_trap',
        mnemonic='MSET',
        desc='MSET in normal mode: vectors through PSAP+0x08, unlike other privileged instructions',
        tags=['segmented', 'seg0', 'trap', 'privileged', 'psa', 'mset_anomaly'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x2100, 0x0000,
              0x2101, 0x8000, 0x7D1A, 0x7B08,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000},
        memory=dict(PSA_BOTH),
        # part: R0=0xE0E0 (via PSAP+0x08), not 0xB0B0
    ))

    # ---- Test 29: no unaligned PSA address is ever formed ----
    # z8000.md 7.7.3 says the PSAP low byte "is assumed to contain zeros; thus
    # the Program Status Area must start on a 256-byte address boundary".
    #
    # What this test settles is narrow and worth stating exactly: the low byte
    # never reaches the address the part fetches a program status block from.
    # It does NOT settle where the byte is dropped.  Two implementations are
    # observationally identical from software:
    #
    #   masked on the write   - the register holds 0x0800 and there is nothing
    #                           left to align by the time the PSA is addressed
    #   kept, masked at use   - the register holds 0x0880 and the address
    #                           computation drops the byte
    #
    # LDCTL is the only way to write PSAP, so if the write masks then a
    # non-zero low byte cannot exist in the register and "alignment at use"
    # has nothing to act on.  The distinction is unobservable through the
    # instruction set, not merely untested - seg_ldctl_psapoff_lowbyte already
    # shows a write of 0x08FF reading back as 0x0800, and both models predict
    # that too.  MAME and z8000_emu take opposite routes and agree here.
    #
    # Write 0x0880 - a low byte that is non-zero but still word aligned - and
    # take a system call with both candidate entries populated:
    #
    #   low byte not in the address -> base 0x0800 -> entry 0x0818 -> R0=0xA11D
    #   low byte in the address     -> base 0x0880 -> entry 0x0898 -> R0=0x0FF5
    #
    # The captured trace records the address actually read, so the marker and
    # the trace agree or the test is wrong.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 0880           ld   r1,#0x880
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0xf00
    #   212: 2100 0000           ld   r0,#0x0
    #   216: 7f00                sc   #0x0
    #   218: 2100 dead           ld   r0,#0xdead          (only if no trap)
    #   21c: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_psap_no_unaligned_psa',
        mnemonic='SC',
        desc='SC with PSAPOFF=0x0880: the reserved low byte never reaches the PSA address',
        tags=['segmented', 'seg0', 'sc', 'trap', 'psa', 'psap', 'alignment'],
        code=[0x2101, 0x0880, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x2100, 0x0000, 0x7F00,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000},
        memory={
            # handler A - reached if the low byte is dropped (base 0x0800)
            0x0300: 0x2100, 0x0302: 0xA11D, 0x0304: 0x5E08, 0x0306: 0x00C0,
            # handler B - reached if the full offset is used (base 0x0880)
            0x0320: 0x2100, 0x0322: 0x0FF5, 0x0324: 0x5E08, 0x0326: 0x00C0,
            # SC entry for the aligned base: 0x0800 + 0x18
            0x0818: 0x0000, 0x081A: 0xC000, 0x081C: 0x8000, 0x081E: 0x0300,
            # SC entry for the unaligned base: 0x0880 + 0x18
            0x0898: 0x0000, 0x089A: 0xC000, 0x089C: 0x8000, 0x089E: 0x0320,
        },
    ))
    tests[-1].observe_memory = [0x0818, 0x0898]

    # ---- Tests 30/31: does PSAPSEG reach the PSA address? ----
    # seg_mame_ldctl_psapseg_mask shows the register reads back whatever was
    # written - 0xFFFF in, 0xFFFF out - so nothing is masked on the way in or
    # out.  That says nothing about the address the part forms when it fetches
    # a program status block, which is the question that matters.
    #
    # The harness banks BRAM as {sn[0], addr[11:0]}, so segment 0 and segment 1
    # are distinguishable and everything above bit 8 of the segment number
    # aliases away.  That is enough to see whether the segment is honoured:
    # put the SC entry in segment 1 and a decoy at the same offset in segment
    # 0, and let the marker say which one was read.
    #
    #   PSAPSEG=0x8100 -> segment 1 -> BRAM 0x1818 -> handler 0x300 -> 0xACE1
    #   segment ignored -> segment 0 -> BRAM 0x0818 -> handler 0x320 -> 0xACE0
    #
    # Both PSA entries name a handler in segment 0, so only the PSA fetch
    # differs.  The trace's segment bit records the bank actually read.
    PSAPSEG_BOTH = {
        # handler reached when the PSA is read from segment 1
        0x0300: 0x2100, 0x0302: 0xACE1, 0x0304: 0x5E08, 0x0306: 0x00C0,
        # handler reached when the segment is dropped and segment 0 is used
        0x0320: 0x2100, 0x0322: 0xACE0, 0x0324: 0x5E08, 0x0326: 0x00C0,
        # SC entry in segment 1 (flat BRAM 0x1800 + 0x18)
        0x1818: 0x0000, 0x181A: 0xC000, 0x181C: 0x8000, 0x181E: 0x0300,
        # SC entry in segment 0, same offset - the decoy
        0x0818: 0x0000, 0x081A: 0xC000, 0x081C: 0x8000, 0x081E: 0x0320,
    }

    # ---- Test 30: segment honoured, bit 15 set (the form every other test uses) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8100           ld   r1,#0x8100
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0xf00
    #   212: 2100 0000           ld   r0,#0x0
    #   216: 7f00                sc   #0x0
    #   218: 2100 dead           ld   r0,#0xdead          (only if no trap)
    #   21c: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_psapseg_segment_used',
        mnemonic='SC',
        desc='SC with PSAPSEG=0x8100: is the PSA fetched from segment 1?',
        tags=['segmented', 'seg1', 'sc', 'trap', 'psa', 'psapseg'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8100, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x2100, 0x0000, 0x7F00,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000},
        memory=dict(PSAPSEG_BOTH),
    ))

    # ---- Test 31: same, with bit 15 clear ----
    # Every segmented pointer this suite builds carries bit 15, because that is
    # what LDA emits for the long form.  PSAPSEG is written by hand, so whether
    # the part needs the bit is a separate question: if it is part of the
    # decode, clearing it should change where the PSA is read from.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   206: 2101 0100           ld   r1,#0x100      (bit 15 clear)
    tests.append(_tc(
        name='seg_psapseg_bit15_clear',
        mnemonic='SC',
        desc='SC with PSAPSEG=0x0100: is bit 15 needed for the segment to decode?',
        tags=['segmented', 'seg1', 'sc', 'trap', 'psa', 'psapseg'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x0100, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x2100, 0x0000, 0x7F00,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000},
        memory=dict(PSAPSEG_BOTH),
    ))

    # ---- Test 32: what segment word does a trap push for a PC in segment 1? ----
    # Every trap capture so far runs in segment 0 and pushes 0x8000, which
    # shows bit 15 is set but cannot show whether the segment field is filled
    # in beside it - segment 0 is all zeros either way.
    #
    # This one jumps into segment 1 and takes the system call there, so the
    # pushed PC segment discriminates:
    #
    #   0x8100  bit 15 set and the segment present - what addr_to_reg does
    #   0x0100  segment present, bit 15 only appears for segment 0
    #   0x8000  segment dropped from the pushed value entirely
    #
    # Note the asymmetry this probes.  seg_psapseg_bit15_clear shows the part
    # does NOT require bit 15 on input - PSAPSEG 0x0100 decodes to segment 1
    # exactly as 0x8100 does - so what it emits is a separate question from
    # what it accepts.  This also covers PUSH_PC on the segmented path, which
    # nothing else reaches.
    #
    # The handler and the PSA stay in segment 0; only the trapping instruction
    # moves.  The pushed frame is read back rather than inferred.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, .text=0x200, .s1=seg1:0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0xf00
    #   212: 2100 0000           ld   r0,#0x0
    #   216: 5e08 8100 0200      jp   t,0x1000200   (segment 1, offset 0x200)
    # seg1:0200: 7f00            sc   #0x0
    # seg1:0202: 2100 dead       ld   r0,#0xdead          (only if no trap)
    # seg1:0206: 5e08 00c0       jp   t,0xc0
    tests.append(_tc(
        name='seg_push_pcseg_from_seg1',
        mnemonic='SC',
        desc='SC taken in segment 1: what PC-segment word does the trap push?',
        tags=['segmented', 'seg1', 'sc', 'trap', 'psa', 'push_pc'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x2100, 0x0000,
              0x5E08, 0x8100, 0x0200],
        regs={0: 0x0000, 1: 0x0000},
        memory={
            # trapping code in segment 1.  The assembler writes this address
            # 0x1000200; the harness addresses BRAM flat as {sn[0], addr[11:0]}
            # so the preload goes at 0x1200.
            0x1200: 0x7F00,
            0x1202: 0x2100, 0x1204: 0xDEAD,
            0x1206: 0x5E08, 0x1208: 0x00C0,
            # handler in segment 0
            0x0300: 0x2100, 0x0302: 0xBEE1,
            0x0304: 0x5E08, 0x0306: 0x00C0,
            # SC entry in segment 0
            0x0818: 0x0000, 0x081A: 0xC000, 0x081C: 0x8000, 0x081E: 0x0300,
        },
    ))
    # the pushed frame is the point of the test - read it back rather than
    # trusting the register dump alone
    tests[-1].observe_memory = [0x0EF8, 0x0EFA, 0x0EFC, 0x0EFE]

    # ---- Test 33: does anything mask NSPOFF / NSPSEG? ----
    # The normal stack pointer is only reachable from System mode, through
    # LDCTL (z8000.md 4.3.3), so unlike R15 it has no direct path.  PSAPOFF
    # turned out to be the one control register either emulator masks; this
    # asks the same of NSP, which neither masks today.
    #
    # Write 0xFFFF and 0xAA55 and read both halves straight back.  A value
    # that returns unchanged means nothing is dropped on the way in or out.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 ffff           ld   r1,#0xffff
    #   204: 7d1f                ldctl nspoff,r1
    #   206: 2101 aa55           ld   r1,#0xaa55
    #   20a: 7d1e                ldctl nspseg,r1
    #   20c: 2102 0000           ld   r2,#0x0
    #   210: 7d27                ldctl r2,nspoff
    #   212: 2103 0000           ld   r3,#0x0
    #   216: 7d36                ldctl r3,nspseg
    #   218: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_ldctl_nsp_roundtrip',
        mnemonic='LDCTL',
        desc='LDCTL NSPOFF/NSPSEG write then read: is either half masked?',
        tags=['segmented', 'control', 'ldctl', 'nsp'],
        code=[0x2101, 0xFFFF, 0x7D1F,
              0x2101, 0xAA55, 0x7D1E,
              0x2102, 0x0000, 0x7D27,
              0x2103, 0x0000, 0x7D36,
              0x5E08, 0x00C0],
        regs={1: 0x0000, 2: 0x0000, 3: 0x0000},
        # unmasked: R2=0xFFFF R3=0xAA55
    ))

    # ---- Test 34: is NSP the same register R15 names in Normal mode? ----
    # z8000.md 4.3.3: "When in Normal mode, a reference by an instruction to
    # the Stack Pointer register will access the Normal mode Stack Pointer",
    # and 2.6: "In System-mode operation, the system stack pointer is directly
    # accessed as a general-purpose register.  The normal stack pointer can be
    # accessed as a special control register."  So NSPOFF written through
    # LDCTL and R15 read in Normal mode should be one register.
    #
    # Set NSP to 0x0E00 in System mode, drop S/N, read R15 into R0, then take
    # a system call to get back to System mode so the dump routine can run -
    # LDCTL is privileged, so there is no way back without a trap.  R0 carries
    # the answer across.
    #
    #   R0 = 0x0E00  -> R15 in Normal mode is the normal stack pointer
    #   R0 = 0x0F00  -> R15 still reads the system stack pointer
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0xf00        (system stack)
    #   212: 2101 0e00           ld   r1,#0xe00
    #   216: 7d1f                ldctl nspoff,r1        (normal stack)
    #   218: 2101 8000           ld   r1,#0x8000
    #   21c: 7d1e                ldctl nspseg,r1
    #   21e: 2100 0000           ld   r0,#0x0
    #   222: 2101 8000           ld   r1,#0x8000
    #   226: 7d1a                ldctl fcw,r1           (Normal mode)
    #   228: a1f0                ld   r0,r15            (which SP is this?)
    #   22a: 7f00                sc   #0x0              (back to System mode)
    #   22c: 2100 dead           ld   r0,#0xdead        (only if no trap)
    #   230: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_nsp_is_normal_r15',
        mnemonic='LDCTL',
        desc='R15 read in Normal mode: is it the NSP set through LDCTL?',
        tags=['segmented', 'control', 'ldctl', 'nsp', 'trap'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00,
              0x2101, 0x0E00, 0x7D1F, 0x2101, 0x8000, 0x7D1E,
              0x2100, 0x0000, 0x2101, 0x8000, 0x7D1A,
              0xA1F0, 0x7F00,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000},
        memory={
            # handler just returns to the dump routine
            0x0300: 0x5E08, 0x0302: 0x00C0,
            # SC entry
            0x0818: 0x0000, 0x081A: 0xC000, 0x081C: 0x8000, 0x081E: 0x0300,
        },
    ))

    # ---- Test 35: does a Normal-mode push realign an odd NSP? ----
    # mame_push_odd_sp settled this for the system stack: from 0x0F01 a PUSH
    # leaves 0x0EFF, so the pointer moves by exactly the operand size and is
    # not folded back to even.  NSP is a separate register reached a separate
    # way, so it is assumed to match rather than known to.
    #
    # Set NSP odd at 0x0E01 while the system stack stays at 0x0F00, drop S/N,
    # and push from Normal mode where RR14 names the normal pointer.  Then
    # take a system call to get back - LDCTL is privileged, so a trap is the
    # only way - and read NSP back in the handler.
    #
    # The pushed value has distinguishable bytes: the high and low register
    # halves are wired to the high and low byte lanes of RAM, so a palindrome
    # could not tell a correct write from a swapped or duplicated one.
    #
    #   R2 = 0x0DFF  moved by exactly 2, as the system stack does
    #   R2 = 0x0DFE  realigned to even first
    #
    # The pushed word is observed too: at 0x0DFF if the pointer was used as
    # given, at 0x0DFE if it was aligned.  Note the bus masks the low address
    # bit on a word access, so the two land in the same word of memory - the
    # pointer left in NSP is what discriminates, and the memory readback is
    # only a cross-check that the push happened at all.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0xf00        (system stack, even)
    #   212: 2101 0e01           ld   r1,#0xe01
    #   216: 7d1f                ldctl nspoff,r1        (normal stack, ODD)
    #   218: 2101 8000           ld   r1,#0x8000
    #   21c: 7d1e                ldctl nspseg,r1
    #   21e: 2100 1234           ld   r0,#0x1234
    #   222: 2101 8000           ld   r1,#0x8000
    #   226: 7d1a                ldctl fcw,r1           (Normal mode)
    #   228: 93e0                push @rr14,r0          (pushes on NSP)
    #   22a: 7f00                sc   #0x0              (back to System mode)
    #   22c: 2100 dead           ld   r0,#0xdead        (only if no trap)
    #   230: 5e08 00c0           jp   t,0xc0
    # Handler at 0x300:
    #   300: 7d27                ldctl r2,nspoff
    #   302: 7d36                ldctl r3,nspseg
    #   304: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_nsp_odd_push',
        mnemonic='PUSH',
        desc='PUSH in Normal mode with NSP odd (0x0E01): does the pointer realign?',
        tags=['segmented', 'seg0', 'push', 'stack', 'nsp', 'alignment', 'trap'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00,
              0x2101, 0x0E01, 0x7D1F, 0x2101, 0x8000, 0x7D1E,
              0x2100, 0x1234, 0x2101, 0x8000, 0x7D1A,
              0x93E0, 0x7F00,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000, 2: 0x0000, 3: 0x0000},
        memory={
            # handler reads NSP back before returning to the dump routine
            0x0300: 0x7D27, 0x0302: 0x7D36, 0x0304: 0x5E08, 0x0306: 0x00C0,
            # SC entry
            0x0818: 0x0000, 0x081A: 0xC000, 0x081C: 0x8000, 0x081E: 0x0300,
            # normal stack landing area, preloaded so a push is visible
            0x0DFE: 0x0000,
        },
    ))
    tests[-1].observe_memory = [0x0DFE]

    # ---- Test 36: segmented System-mode push through RR14 with an odd offset ----
    # This is the shape the S8000 monitor uses and the one no capture covered.
    # mame_push_odd_sp pushes through @R15 in NONSEGMENTED mode; seg_nsp_odd_push
    # pushes through @RR14 but in Normal mode against the NSP.  The monitor does
    # neither - it runs System mode, segmented, and deliberately lands the system
    # stack on an odd offset:
    #
    #     0023A8: add   r15,#%0009      -> R15 = 0x408D
    #     0023AC: push  @r15,r2         -> R15 = 0x408A  (moves by THREE)
    #
    # Moving by three is a realignment to even.  MAME did that through
    # ADD_ALIGNED16 and the monitor boots; with the macro removed it moves by
    # two, the stack stays odd, and every later trap frame is a byte out.
    #
    # The offset is built with LDA and then incremented rather than written as a
    # literal, so no segmented pointer is hand-coded.
    #
    #   R4 = 0x0EFF  moved by exactly 2, pointer left odd
    #   R4 = 0x0EFE  realigned to even
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 760e 8000 0f00      lda  rr14,0xf00
    #   206: a9f0                inc  r15,#0x1          (system stack -> odd)
    #   208: 2102 1234           ld   r2,#0x1234
    #   20c: 93e2                push @rr14,r2
    #   20e: a1f4                ld   r4,r15            (capture the pointer)
    #   210: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_push_odd_sp_sys',
        mnemonic='PUSH',
        desc='PUSH @RR14 in System mode with an odd stack offset: does the pointer realign?',
        tags=['segmented', 'seg0', 'push', 'stack', 'alignment'],
        code=[0x760E, 0x8000, 0x0F00,
              0xA9F0,
              0x2102, 0x1234,
              0x93E2,
              0xA1F4,
              0x5E08, 0x00C0],
        regs={2: 0x0000, 4: 0x0000, 14: 0x0000, 15: 0x0000},
        memory={0x0EFE: 0x0000},
    ))
    tests[-1].observe_memory = [0x0EFE]

    # ---- Test 37: trap taken with the stack ALREADY odd ----
    # The PUSH instruction is now pinned in three shapes and never realigns -
    # mame_push_odd_sp, seg_nsp_odd_push, seg_push_odd_sp_sys all move the
    # pointer by exactly the operand size and land the word, lanes intact, at
    # the masked even address.  The trap sequence is a different mechanism and
    # every trap capture so far starts from an EVEN stack, so nothing says
    # whether a trap frame aligns itself.
    #
    # This matters for the S8000 monitor.  It reaches an odd system stack
    # deliberately - "add r15,#9" after an interrupt frame - and then takes
    # traps against it.  If the trap sequence aligns the frame, the handler's
    # "cpb %0001(r15),#..." reads the identifier byte it expects; if it does
    # not, every field of the frame is a byte out.
    #
    # Set the stack odd with LDA + INC (no hand-coded segmented pointer), take
    # SC #0, and have the handler report the stack pointer it was given.
    #
    #   R4 = 0x0EF9  frame pushed from the odd pointer, not aligned
    #                (0x0F01 - 8)
    #   R4 = 0x0EF8  the trap sequence aligned first, as the monitor needs
    #                (0x0F00 - 8)
    #
    # R5 carries the segment half as a control; the frame words are read back
    # so the identifier can be located whichever way it fell.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0xf00
    #   212: a9f0                inc  r15,#0x1          (system stack -> ODD)
    #   214: 2100 0000           ld   r0,#0x0
    #   218: 7f00                sc   #0x0
    #   21a: 2100 dead           ld   r0,#0xdead        (only if no trap)
    #   21e: 5e08 00c0           jp   t,0xc0
    # Handler at 0x300:
    #   300: a1f4                ld   r4,r15            (stack the trap gave us)
    #   302: a1e5                ld   r5,r14
    #   304: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_trap_push_odd_sp',
        mnemonic='SC',
        desc='SC with the system stack already odd: does the trap frame align itself?',
        tags=['segmented', 'seg0', 'sc', 'trap', 'stack', 'alignment'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00,
              0xA9F0,
              0x2100, 0x0000,
              0x7F00,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000, 4: 0x0000, 5: 0x0000},
        memory={
            # handler reports the stack pointer the trap handed it
            0x0300: 0xA1F4, 0x0302: 0xA1E5, 0x0304: 0x5E08, 0x0306: 0x00C0,
            # SC entry
            0x0818: 0x0000, 0x081A: 0xC000, 0x081C: 0x8000, 0x081E: 0x0300,
        },
    ))
    # read back both candidate frame positions so the identifier can be found
    tests[-1].observe_memory = [0x0EF6, 0x0EF8, 0x0EFA, 0x0EFC, 0x0EFE, 0x0F00]

    # ---- Tests 38-44: does bit 15 of the PC segment word follow the PC load? ----
    # Every capture so far reaches its code through a segment word with bit 15
    # set: the bootstrap's `jp test_code` (5e08 8000 0200), long-form JP/CALL,
    # and PSA entries written 0x8000.  With that entry the part emits bit 15
    # set wherever it writes the PC segment back out:
    #
    #   seg_mame_ldar_ra_hiword_poison   LDAR -> R2 = 0x8000 (manual: "all
    #                                    'reserved' bits (bits 16-23 and bit
    #                                    31) cleared to zero", z8000.md LDAR)
    #   seg_push_pcseg_from_seg1         SC in segment 1 pushes 0x8100
    #
    # Those captures cannot tell a constant 1 from a bit that the PC segment
    # register simply keeps from whatever was loaded into it.  The Olivetti
    # L1 M40 OS (OSLEM 7.0+, KIO0 MX82) depends on the difference: its
    # start-up task enters the module with
    #
    #   xor r0,r0 / ldb rh0,rl1 / ld r8,r0   (r8 = 0x0300, bit 15 CLEAR)
    #   jp  @rr8
    #   ldar rr4,...  / ldb <<0>>0x016c,rh4  (stored byte must be 0x03)
    #   ldar rr6,...  / ld r12,r6 / set r12,#15
    #
    # and only works if that LDAR returns 0x0300.  A model that always emits
    # bit 15 (MAME, z8000_emu) stores 0x83 and the OS fails.
    #
    # So these tests load the PC from a segment word with bit 15 CLEAR - by
    # register-indirect JP and by the short-offset direct form - and then read
    # the PC segment back three ways: LDAR, a trap push, and a CALR push.
    # Each bit-15-clear case has a bit-15-set control with the same shape.
    #
    # The 0x0000/0x0100 pointer words are written by hand ON PURPOSE (as in
    # seg_psapseg_bit15_clear): LDA always emits bit 15, and the clear bit is
    # the object of the test.  The control cases use LDA as usual.
    #
    # Candidate readings of the result (R4, or the pushed segment word):
    #   bit 15 clear  the part keeps bit 15 of the PC segment as loaded
    #   bit 15 set    the bit is emitted unconditionally

    # ---- Test 38: LDAR after JP @RR2, pointer bit 15 clear, segment 0 ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 1402 0000 0210      ldl  rr2,#0x210     (seg 0, bit 15 clear)
    #   206: 1e28                jp   t,@rr2
    #   208: 8d07                nop
    #   20a: 8d07                nop
    #   20c: 8d07                nop
    #   20e: 8d07                nop
    #   210: 3404 0004           ldar rr4,0x218
    #   214: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_ldar_pc_ir_b15clr_seg0',
        mnemonic='LDAR',
        desc='LDAR RR4 after JP @RR2 with RR2=0x0000:0210 (PC loaded, bit 15 clear)',
        tags=['segmented', 'seg0', 'ldar', 'ra_mode', 'reserved_bits', 'pcseg_bit15'],
        code=[0x1402, 0x0000, 0x0210, 0x1E28,
              0x8D07, 0x8D07, 0x8D07, 0x8D07,
              0x3404, 0x0004, 0x5E08, 0x00C0],
        regs={4: 0xA5AA, 5: 0x1234},
    ))

    # ---- Test 39: control for 38 - same shape, pointer built by LDA ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7602 8000 0210      lda  rr2,0x210      (seg 0, bit 15 set)
    #   206: 1e28                jp   t,@rr2
    #   208: 8d07                nop
    #   20a: 8d07                nop
    #   20c: 8d07                nop
    #   20e: 8d07                nop
    #   210: 3404 0004           ldar rr4,0x218
    #   214: 5e08 00c0           jp   t,0xc0
    tests.append(_tc(
        name='seg_ldar_pc_ir_b15set_seg0',
        mnemonic='LDAR',
        desc='LDAR RR4 after JP @RR2 with RR2=0x8000:0210 (control, bit 15 set)',
        tags=['segmented', 'seg0', 'ldar', 'ra_mode', 'reserved_bits', 'pcseg_bit15'],
        code=[0x7602, 0x8000, 0x0210, 0x1E28,
              0x8D07, 0x8D07, 0x8D07, 0x8D07,
              0x3404, 0x0004, 0x5E08, 0x00C0],
        regs={4: 0xA5AA, 5: 0x1234},
    ))

    # ---- Test 40: LDAR after JP @RR2 into segment 1, pointer bit 15 clear ----
    # Segment 0 is all zeros beside the bit, so segment 1 shows whether the
    # segment field is filled in next to it (0x0100 / 0x8100 / 0x8000).
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, .text=0x200, .s1=seg1:0x200)
    #   200: 1402 0100 0200      ldl  rr2,#0x1000200 (seg 1, bit 15 clear)
    #   206: 1e28                jp   t,@rr2
    # seg1:0200: 3404 0004       ldar rr4,0x1000208
    # seg1:0204: 5e08 00c0       jp   t,0xc0
    tests.append(_tc(
        name='seg_ldar_pc_ir_b15clr_seg1',
        mnemonic='LDAR',
        desc='LDAR RR4 in segment 1 after JP @RR2 with RR2=0x0100:0200 (bit 15 clear)',
        tags=['segmented', 'seg1', 'ldar', 'ra_mode', 'reserved_bits', 'pcseg_bit15'],
        code=[0x1402, 0x0100, 0x0200, 0x1E28],
        regs={4: 0xA5AA, 5: 0x1234},
        memory={
            # code in segment 1 (BRAM flat {sn[0], addr[11:0]} -> 0x1200)
            SEG1_Z80_ADDR: 0x3404, SEG1_Z80_ADDR + 2: 0x0004,
            SEG1_Z80_ADDR + 4: 0x5E08, SEG1_Z80_ADDR + 6: 0x00C0,
        },
    ))

    # ---- Test 41: control for 40 - pointer built by LDA ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, .text=0x200, .s1=seg1:0x200)
    #   200: 7602 8100 0200      lda  rr2,0x1000200  (seg 1, bit 15 set)
    #   206: 1e28                jp   t,@rr2
    # seg1:0200: 3404 0004       ldar rr4,0x1000208
    # seg1:0204: 5e08 00c0       jp   t,0xc0
    tests.append(_tc(
        name='seg_ldar_pc_ir_b15set_seg1',
        mnemonic='LDAR',
        desc='LDAR RR4 in segment 1 after JP @RR2 with RR2=0x8100:0200 (control)',
        tags=['segmented', 'seg1', 'ldar', 'ra_mode', 'reserved_bits', 'pcseg_bit15'],
        code=[0x7602, 0x8100, 0x0200, 0x1E28],
        regs={4: 0xA5AA, 5: 0x1234},
        memory={
            SEG1_Z80_ADDR: 0x3404, SEG1_Z80_ADDR + 2: 0x0004,
            SEG1_Z80_ADDR + 4: 0x5E08, SEG1_Z80_ADDR + 6: 0x00C0,
        },
    ))

    # ---- Test 42: LDAR after a short-offset direct JP into segment 1 ----
    # The short-offset address word (0x0120 = segment 1, offset 0x20) has
    # bit 15 clear by encoding, so this is the direct-address counterpart of
    # test 40 and needs no hand-made pointer.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, .text=0x200, .s1short=seg1:0x20)
    #   200: 5e08 0120           jp   t,0x1000020    (short-offset form)
    # seg1:0020: 3404 0004       ldar rr4,0x1000028
    # seg1:0024: 5e08 00c0       jp   t,0xc0
    tests.append(_tc(
        name='seg_ldar_pc_da_short_seg1',
        mnemonic='LDAR',
        desc='LDAR RR4 in segment 1 after short-offset JP <<1>>0x20 (address word 0x0120)',
        tags=['segmented', 'seg1', 'ldar', 'ra_mode', 'short_da', 'reserved_bits',
              'pcseg_bit15'],
        code=[0x5E08, 0x0120],
        regs={4: 0xA5AA, 5: 0x1234},
        memory={
            # code at segment 1, offset 0x20 (BRAM flat -> 0x1020)
            0x1020: 0x3404, 0x1022: 0x0004,
            0x1024: 0x5E08, 0x1026: 0x00C0,
        },
    ))

    # ---- Test 43: trap push after JP @RR2 into segment 1, bit 15 clear ----
    # seg_push_pcseg_from_seg1 with the entry changed from the long-form JP
    # (5e08 8100 0200, pushed 0x8100) to a bit-15-clear pointer.  The pushed
    # PC segment word at 0x0EFC is the result.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, .text=0x200, .s1=seg1:0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0xf00
    #   212: 2100 0000           ld   r0,#0x0
    #   216: 1402 0100 0200      ldl  rr2,#0x1000200 (seg 1, bit 15 clear)
    #   21c: 1e28                jp   t,@rr2
    # seg1:0200: 7f00            sc   #0x0
    # seg1:0202: 2100 dead       ld   r0,#0xdead          (only if no trap)
    # seg1:0206: 5e08 00c0       jp   t,0xc0
    tests.append(_tc(
        name='seg_push_pcseg_ir_b15clr_seg1',
        mnemonic='SC',
        desc='SC in segment 1 after JP @RR2 with RR2=0x0100:0200: pushed PC-segment word',
        tags=['segmented', 'seg1', 'sc', 'trap', 'psa', 'push_pc', 'pcseg_bit15'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x2100, 0x0000,
              0x1402, 0x0100, 0x0200, 0x1E28],
        regs={0: 0x0000, 1: 0x0000},
        memory={
            # trapping code in segment 1 (BRAM flat -> 0x1200)
            0x1200: 0x7F00,
            0x1202: 0x2100, 0x1204: 0xDEAD,
            0x1206: 0x5E08, 0x1208: 0x00C0,
            # handler in segment 0
            0x0300: 0x2100, 0x0302: 0xBEE1,
            0x0304: 0x5E08, 0x0306: 0x00C0,
            # SC entry in segment 0
            0x0818: 0x0000, 0x081A: 0xC000, 0x081C: 0x8000, 0x081E: 0x0300,
        },
    ))
    tests[-1].observe_memory = [0x0EF8, 0x0EFA, 0x0EFC, 0x0EFE]

    # ---- Test 44: CALR push after JP @RR2 into segment 1, bit 15 clear ----
    # The return address a call pushes is the third way the PC segment gets
    # written out.  CALR pushes the segment word at 0x0EFC and the offset
    # (0x0202) at 0x0EFE.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, .text=0x200, .s1=seg1:0x200)
    #   200: 760e 8000 0f00      lda  rr14,0xf00
    #   206: 1402 0100 0200      ldl  rr2,#0x1000200 (seg 1, bit 15 clear)
    #   20c: 1e28                jp   t,@rr2
    # seg1:0200: dfff            calr 0x1000204
    # seg1:0202: 8d07            nop
    # seg1:0204: 5e08 00c0       jp   t,0xc0
    tests.append(_tc(
        name='seg_calr_push_ir_b15clr_seg1',
        mnemonic='CALR',
        desc='CALR in segment 1 after JP @RR2 with RR2=0x0100:0200: pushed PC-segment word',
        tags=['segmented', 'seg1', 'calr', 'push_pc', 'pcseg_bit15'],
        code=[0x760E, 0x8000, 0x0F00, 0x1402, 0x0100, 0x0200, 0x1E28],
        memory={
            # code in segment 1 (BRAM flat -> 0x1200)
            0x1200: 0xDFFF, 0x1202: 0x8D07,
            0x1204: 0x5E08, 0x1206: 0x00C0,
        },
    ))
    tests[-1].observe_memory = [0x0EFC, 0x0EFE]

    # ---- Tests 45-48: the other ways a PC segment word is loaded ----
    # Tests 38-44 showed the part keeps bit 15 of the PC segment as loaded by
    # JP (register-indirect and short-offset direct) and writes it back out.
    # These repeat the bit-15-clear case for the remaining load paths - RET,
    # IRET, LDPS and a trap vector fetched from the PSA - each landing on the
    # same segment-1 LDAR, so R4 names the bit the PC took from that path.
    _SEG1_LDAR = {
        # seg1:0200: 3404 0004   ldar rr4,0x1000208
        # seg1:0204: 5e08 00c0   jp   t,0xc0
        SEG1_Z80_ADDR: 0x3404, SEG1_Z80_ADDR + 2: 0x0004,
        SEG1_Z80_ADDR + 4: 0x5E08, SEG1_Z80_ADDR + 6: 0x00C0,
    }

    # ---- Test 45: RET to a pushed address with bit 15 clear ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, .text=0x200, .s1=seg1:0x200)
    #   200: 760e 8000 0f00      lda  rr14,0xf00
    #   206: 1402 0100 0200      ldl  rr2,#0x1000200 (seg 1, bit 15 clear)
    #   20c: 91e2                pushl @rr14,rr2
    #   20e: 9e08                ret  t
    # seg1:0200: 3404 0004       ldar rr4,0x1000208
    # seg1:0204: 5e08 00c0       jp   t,0xc0
    tests.append(_tc(
        name='seg_ldar_pc_ret_b15clr_seg1',
        mnemonic='LDAR',
        desc='LDAR RR4 in segment 1 after RET to pushed 0x0100:0200 (bit 15 clear)',
        tags=['segmented', 'seg1', 'ldar', 'ret', 'reserved_bits', 'pcseg_bit15'],
        code=[0x760E, 0x8000, 0x0F00, 0x1402, 0x0100, 0x0200, 0x91E2, 0x9E08],
        regs={4: 0xA5AA, 5: 0x1234},
        memory=dict(_SEG1_LDAR),
    ))

    # ---- Test 46: IRET to a frame whose PC segment word has bit 15 clear ----
    # seg_iret_basic with the frame's PCSEG changed from 0x8000 to 0x0100.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, .text=0x200, .s1=seg1:0x200)
    #   200: 7b00                iret
    # seg1:0200: 3404 0004       ldar rr4,0x1000208
    # seg1:0204: 5e08 00c0       jp   t,0xc0
    tests.append(_tc(
        name='seg_ldar_pc_iret_b15clr_seg1',
        mnemonic='LDAR',
        desc='LDAR RR4 in segment 1 after IRET with frame PCSEG=0x0100 (bit 15 clear)',
        tags=['segmented', 'seg1', 'ldar', 'iret', 'stack', 'reserved_bits',
              'pcseg_bit15'],
        code=[0x7B00],
        regs={4: 0xA5AA, 5: 0x1234, 14: 0x8000, 15: STACK_BASE},
        memory={
            STACK_BASE: 0x0000,          # Identifier/reserved word
            STACK_BASE + 2: FCW_SEG,     # Restored FCW
            STACK_BASE + 4: 0x0100,      # Return PCSEG: segment 1, bit 15 clear
            STACK_BASE + 6: 0x0200,      # Return PC offset
            **_SEG1_LDAR,
        },
    ))

    # ---- Test 47: LDPS from a block whose PC segment word has bit 15 clear ----
    # seg_ldps_ir_basic through RR6 (RR4 is the result pair) with PCSEG 0x0100.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, .text=0x200, .s1=seg1:0x200)
    #   200: 3960                ldps @rr6
    # seg1:0200: 3404 0004       ldar rr4,0x1000208
    # seg1:0204: 5e08 00c0       jp   t,0xc0
    tests.append(_tc(
        name='seg_ldar_pc_ldps_b15clr_seg1',
        mnemonic='LDAR',
        desc='LDAR RR4 in segment 1 after LDPS @RR6 with block PCSEG=0x0100 (bit 15 clear)',
        tags=['segmented', 'seg1', 'ldar', 'ldps', 'IR_mode', 'reserved_bits',
              'pcseg_bit15'],
        code=[0x3960],
        regs={4: 0xA5AA, 5: 0x1234, 6: 0x8000, 7: SEG0_LONG_ADDR},
        memory={
            SEG0_LONG_ADDR: 0x0000,
            SEG0_LONG_ADDR + 2: FCW_SEG,
            SEG0_LONG_ADDR + 4: 0x0100,  # PCSEG: segment 1, bit 15 clear
            SEG0_LONG_ADDR + 6: 0x0200,
            **_SEG1_LDAR,
        },
    ))

    # ---- Test 48: trap vector whose PC segment word has bit 15 clear ----
    # seg_sc_basic with the SC entry's PCSEG changed from 0x8000 to 0x0100, so
    # the handler is the segment-1 LDAR.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, .text=0x200, .s1=seg1:0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0xf00
    #   212: 7f00                sc   #0x0
    #   214: 2100 dead           ld   r0,#0xdead          (only if no trap)
    #   218: 5e08 00c0           jp   t,0xc0
    # seg1:0200: 3404 0004       ldar rr4,0x1000208
    # seg1:0204: 5e08 00c0       jp   t,0xc0
    tests.append(_tc(
        name='seg_ldar_pc_trap_b15clr_seg1',
        mnemonic='LDAR',
        desc='LDAR RR4 in a segment-1 SC handler entered through PSA PCSEG=0x0100',
        tags=['segmented', 'seg1', 'ldar', 'sc', 'trap', 'psa', 'reserved_bits',
              'pcseg_bit15'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x7F00,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000, 4: 0xA5AA, 5: 0x1234},
        memory={
            # SC entry: reserved(+0), FCW(+2), PCSEG(+4), PC_off(+6)
            0x0818: 0x0000, 0x081A: 0xC000, 0x081C: 0x0100, 0x081E: 0x0200,
            **_SEG1_LDAR,
        },
    ))

    # =====================================================================
    # DISABLED: odd-stack-pointer tests.  UNRESOLVED CONFLICT -- see the
    # long note in gen_mame_fixes.py before acting on these.
    #
    # The rig measured symmetric SP arithmetic from an odd SP (the pointer
    # keeps bit 0; only the bus address is even), but the S8000 monitor's
    # segment-trap handler only balances if a push from an odd SP realigns,
    # and the boot demonstrably breaks without that.  Which part behaves
    # which way is NOT established -- the mask-revision explanation is a
    # hypothesis awaiting a capture on an early-date-code Z8001.
    # Excluded, never deleted: these are valid silicon measurements.
    # =====================================================================
    _DISABLED_ODD_SP = {
        'seg_nsp_odd_push',
        'seg_push_odd_sp_sys',
        'seg_trap_push_odd_sp',
    }
    tests = [t for t in tests if t.name not in _DISABLED_ODD_SP]

    return tests
