"""Segmented mode test generator for Z8001.

Generates TestCase objects for Z8001 segmented addressing tests.
All instruction encodings are pre-assembled with z8k-coff-as -z8001 and
verified with z8k-coff-objdump. Code words are hardcoded below with
assembler-verified listing comments.

**** IMPORTANT: NEVER hand-code Z8001 segmented values. ****
**** This includes opcodes, DA words, AND register pair values for ****
**** segmented pointers (e.g. @RRn). The encoding is NOT obvious: ****
****   segment 1, offset 0x200 in a register pair = R_even=0x8100, ****
****   R_odd=0x0200 (bit 15=1 for long-form, segment in bits 14:8). ****
**** ALWAYS use the assembler (LDA instruction) to generate segmented ****
**** pointer values in test code. See CLAUDE.md. ****
****                                                                ****
**** To re-verify encodings, assemble with:                         ****
****   z8k-coff-as -z8001 test.s -o test.o                         ****
****   z8k-coff-ld -mz8001 -T test.ld test.o -o test.elf           ****
****   z8k-coff-objdump -d test.elf                                 ****
**** using the linker script described in the section comments.     ****

Usage:
    from tests.gen_segmented import generate_segmented_tests
    tests = generate_segmented_tests()
"""

from .defs import TestCase
from .helpers import OPERAND_BASE, STACK_BASE

# Segmented FCW: System + Segmented
FCW_SEG = 0xC000

# Segment 0 short-form data address (offset < 256, in gap of bootstrap area)
SEG0_SHORT_ADDR = 0x00B4

# Segment 0 long-form data address (offset >= 256)
SEG0_LONG_ADDR = OPERAND_BASE  # 0x0400

# Segment 1 data base offset and corresponding Z80/BRAM address
SEG1_DATA_OFFSET = 0x0200
SEG1_Z80_ADDR = 0x1200  # Z80 flat address for segment 1, offset 0x0200

# Linker script used to generate the code words below:
#   OUTPUT_FORMAT("coff-z8k")
#   OUTPUT_ARCH("z8001")
#   MEMORY {
#       SEG0 : ORIGIN = 0x00000, LENGTH = 4K
#       SEG1 : ORIGIN = 0x10000, LENGTH = 4K
#   }
#   SECTIONS {
#       .text    0x00200 : { *(.text)    } > SEG0
#       .s0short 0x000B4 : { *(.s0short) } > SEG0
#       .s0long  0x00400 : { *(.s0long)  } > SEG0
#       .s0stk   0x00F00 : { *(.s0stk)   } > SEG0
#       .s1data  0x10200 : { *(.s1data)  } > SEG1
#   }


def _tc(name, mnemonic, desc, tags, code, regs=None, memory=None,
        expected_regs=None, expected_memory=None):
    """Create a segmented test case."""
    return TestCase(
        name=name,
        mnemonic=mnemonic,
        description=desc,
        tags=["systematic", "segmented"] + tags,
        target="z8001-seg",
        code=code,
        regs=regs or {},
        fcw=FCW_SEG,
        memory=memory or {},
        expected_regs=expected_regs or {},
        expected_memory=expected_memory or {},
    )


def generate_segmented_tests():
    """Generate segmented mode tests for Z8001.

    Returns a list of TestCase objects with assembler-verified instruction
    encodings for segmented DA mode. All code words were generated by
    z8k-coff-as -z8001 and verified with z8k-coff-objdump.
    """
    tests = []

    # ---- Test 1: LD R0 from segment 0, short-form DA ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0short=0xB4)
    #   200: 6100 8000 00b4    ld   r0,0xb4
    tests.append(_tc(
        name='seg_ld_r_seg0_short',
        mnemonic='LD',
        desc='LD R0, seg0:0xB4 (short-form DA)',
        tags=['segmented', 'seg0', 'short_da'],
        code=[0x6100, 0x8000, 0x00B4],
        regs={0: 0x0000},
        memory={SEG0_SHORT_ADDR: 0xBEEF},
    ))

    # ---- Test 2: ST R0 to segment 0, short-form DA ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0short=0xB4)
    #   200: 6f00 8000 00b4    ld   0xb4,r0
    tests.append(_tc(
        name='seg_st_r_seg0_short',
        mnemonic='ST',
        desc='ST R0, seg0:0xB4 (short-form DA)',
        tags=['segmented', 'seg0', 'short_da'],
        code=[0x6F00, 0x8000, 0x00B4],
        regs={0: 0xCAFE},
        memory={},
    ))
    tests[-1].expected_memory = {SEG0_SHORT_ADDR: 0xCAFE}

    # ---- Test 3: LD R0 from segment 0, long-form DA ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 6100 8000 0400    ld   r0,0x400
    tests.append(_tc(
        name='seg_ld_r_seg0_long',
        mnemonic='LD',
        desc='LD R0, seg0:0x400 (long-form DA)',
        tags=['segmented', 'seg0', 'long_da'],
        code=[0x6100, 0x8000, 0x0400],
        regs={0: 0x0000},
        memory={SEG0_LONG_ADDR: 0xDEAD},
    ))

    # ---- Test 4: ST R0 to segment 0, long-form DA ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 6f00 8000 0400    ld   0x400,r0
    tests.append(_tc(
        name='seg_st_r_seg0_long',
        mnemonic='ST',
        desc='ST R0, seg0:0x400 (long-form DA)',
        tags=['segmented', 'seg0', 'long_da'],
        code=[0x6F00, 0x8000, 0x0400],
        regs={0: 0xFACE},
        memory={},
    ))
    tests[-1].expected_memory = {SEG0_LONG_ADDR: 0xFACE}

    # ---- Test 5: LD R0 from segment 1 (cross-segment) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 6100 8100 0200    ld   r0,0x1000200
    tests.append(_tc(
        name='seg_ld_r_seg1',
        mnemonic='LD',
        desc='LD R0, seg1:0x200 (cross-segment load)',
        tags=['segmented', 'seg1', 'cross_segment'],
        code=[0x6100, 0x8100, 0x0200],
        regs={0: 0x0000},
        memory={SEG1_Z80_ADDR: 0x1234},
    ))

    # ---- Test 6: ST R0 to segment 1 (cross-segment) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 6f00 8100 0200    ld   0x1000200,r0
    tests.append(_tc(
        name='seg_st_r_seg1',
        mnemonic='ST',
        desc='ST R0, seg1:0x200 (cross-segment store)',
        tags=['segmented', 'seg1', 'cross_segment'],
        code=[0x6F00, 0x8100, 0x0200],
        regs={0: 0xABCD},
        memory={},
    ))
    tests[-1].expected_memory = {SEG1_Z80_ADDR: 0xABCD}

    # ---- Test 7: LDB RH0 from segment 1 (byte load) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 6000 8100 0200    ldb  rh0,0x1000200
    tests.append(_tc(
        name='seg_ldb_rh0_seg1',
        mnemonic='LDB',
        desc='LDB RH0, seg1:0x200 (byte load cross-segment)',
        tags=['segmented', 'seg1', 'byte', 'cross_segment'],
        code=[0x6000, 0x8100, 0x0200],
        regs={0: 0x0000},
        memory={SEG1_Z80_ADDR: 0xAB00},
    ))

    # ---- Test 8: STB RH0 to segment 1 (byte store) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 6e00 8100 0200    ldb  0x1000200,rh0
    tests.append(_tc(
        name='seg_stb_rh0_seg1',
        mnemonic='STB',
        desc='STB RH0, seg1:0x200 (byte store cross-segment)',
        tags=['segmented', 'seg1', 'byte', 'cross_segment'],
        code=[0x6E00, 0x8100, 0x0200],
        regs={0: 0xCD00},
        memory={SEG1_Z80_ADDR: 0x0000},
    ))
    tests[-1].expected_memory = {SEG1_Z80_ADDR: 0xCD00}

    # ---- Test 9: LD R0, @RR2 (indirect, segment 0) ----
    # RR2 set up by LDA in code — never hand-code segmented pointer registers
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 7602 8000 0400    lda  rr2,0x400
    #   206: 2120              ld   r0,@rr2
    tests.append(_tc(
        name='seg_ld_r_ir_seg0',
        mnemonic='LD',
        desc='LD R0, @RR2 (indirect, seg 0 offset 0x400)',
        tags=['segmented', 'seg0', 'indirect'],
        code=[0x7602, 0x8000, 0x0400, 0x2120],
        regs={0: 0x0000},
        memory={SEG0_LONG_ADDR: 0x9876},
    ))

    # ---- Test 10: LD R0, @RR2 (indirect, segment 1) ----
    # RR2 set up by LDA in code — never hand-code segmented pointer registers
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 7602 8100 0200    lda  rr2,0x1000200
    #   206: 2120              ld   r0,@rr2
    tests.append(_tc(
        name='seg_ld_r_ir_seg1',
        mnemonic='LD',
        desc='LD R0, @RR2 (indirect, seg 1 offset 0x200)',
        tags=['segmented', 'seg1', 'indirect', 'cross_segment'],
        code=[0x7602, 0x8100, 0x0200, 0x2120],
        regs={0: 0x0000},
        memory={SEG1_Z80_ADDR: 0x5432},
    ))

    # ---- Test 11: ST R0, @RR2 (indirect store, segment 1) ----
    # RR2 set up by LDA in code — never hand-code segmented pointer registers
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 7602 8100 0200    lda  rr2,0x1000200
    #   206: 2f20              ld   @rr2,r0
    tests.append(_tc(
        name='seg_st_r_ir_seg1',
        mnemonic='ST',
        desc='ST R0, @RR2 (indirect store, seg 1 offset 0x200)',
        tags=['segmented', 'seg1', 'indirect', 'cross_segment'],
        code=[0x7602, 0x8100, 0x0200, 0x2F20],
        regs={0: 0xFEDC},
        memory={},
    ))
    tests[-1].expected_memory = {SEG1_Z80_ADDR: 0xFEDC}

    # ---- Test 12: LD R0, addr(R5) segment 0 (indexed) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 6150 8000 0400    ld   r0,0x400(r5)
    tests.append(_tc(
        name='seg_ld_r_x_seg0',
        mnemonic='LD',
        desc='LD R0, seg0:0x400(R5) (indexed, R5=4)',
        tags=['segmented', 'seg0', 'indexed'],
        code=[0x6150, 0x8000, 0x0400],
        regs={0: 0x0000, 5: 0x0004},
        memory={SEG0_LONG_ADDR + 4: 0x4321},
    ))

    # ---- Test 13: LD R0, addr(R5) segment 1 (indexed, cross-segment) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 6150 8100 0200    ld   r0,0x1000200(r5)
    tests.append(_tc(
        name='seg_ld_r_x_seg1',
        mnemonic='LD',
        desc='LD R0, seg1:0x200(R5) (indexed, R5=6)',
        tags=['segmented', 'seg1', 'indexed', 'cross_segment'],
        code=[0x6150, 0x8100, 0x0200],
        regs={0: 0x0000, 5: 0x0006},
        memory={SEG1_Z80_ADDR + 6: 0x8765},
    ))

    # ---- Test 14: Segment isolation ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2100 aaaa         ld   r0,#0xaaaa
    #   204: 6f00 8000 0400    ld   0x400,r0
    #   20a: 2100 5555         ld   r0,#0x5555
    #   20e: 6f00 8100 0200    ld   0x1000200,r0
    #   214: 6101 8000 0400    ld   r1,0x400
    #   21a: 6102 8100 0200    ld   r2,0x1000200
    tests.append(_tc(
        name='seg_isolation',
        mnemonic='ST',
        desc='Write seg0:0x400=0xAAAA, seg1:0x200=0x5555, verify both',
        tags=['segmented', 'seg0', 'seg1', 'cross_segment', 'isolation'],
        code=[0x2100, 0xAAAA, 0x6F00, 0x8000, 0x0400,
              0x2100, 0x5555, 0x6F00, 0x8100, 0x0200,
              0x6101, 0x8000, 0x0400, 0x6102, 0x8100, 0x0200],
        regs={0: 0x0000, 1: 0x0000, 2: 0x0000},
        memory={SEG0_LONG_ADDR: 0x0000, SEG1_Z80_ADDR: 0x0000},
    ))
    tests[-1].expected_memory = {
        SEG0_LONG_ADDR: 0xAAAA,
        SEG1_Z80_ADDR: 0x5555,
    }

    # ---- Test 15: JP label (intra-segment) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2100 1234         ld   r0,#0x1234
    #   204: 5e08 8000 020e    jp   t,0x20e
    #   20a: 2100 dead         ld   r0,#0xdead       (skipped)
    #   20e: 2101 5678         ld   r1,#0x5678        (target)
    tests.append(_tc(
        name='seg_jp_seg0',
        mnemonic='JP',
        desc='JP target (intra-segment jump, skip one instruction)',
        tags=['segmented', 'seg0', 'branch'],
        code=[0x2100, 0x1234, 0x5E08, 0x8000, 0x020E,
              0x2100, 0xDEAD, 0x2101, 0x5678],
        regs={0: 0x0000, 1: 0x0000},
    ))

    # ---- Test 16: CALL/RET (segment 0) ----
    # RR14 stack pointer set up by LDA — never hand-code segmented pointers
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0stk=0xF00)
    #   200: 760e 8000 0f00    lda  rr14,0xf00
    #   206: 2100 0000         ld   r0,#0x0
    #   20a: 5f00 8000 021a    call 0x21a
    #   210: 2100 aaaa         ld   r0,#0xaaaa
    #   214: 5e08 8000 0220    jp   t,0x220           (done)
    #   21a: 2100 1234         ld   r0,#0x1234        (subroutine)
    #   21e: 9e08              ret
    #   220:                                          (done label)
    # CALL at 0x20A is 6 bytes (seg long-form), return address = 0x210
    # Stack residue after RET: PCSEG at SP-4, offset at SP-2
    tests.append(_tc(
        name='seg_call_ret_seg0',
        mnemonic='CALL',
        desc='CALL subroutine / RET (segmented stack)',
        tags=['segmented', 'seg0', 'call', 'ret'],
        code=[0x760E, 0x8000, 0x0F00, 0x2100, 0x0000,
              0x5F00, 0x8000, 0x021A, 0x2100, 0xAAAA,
              0x5E08, 0x8000, 0x0220, 0x2100, 0x1234, 0x9E08],
        regs={0: 0x0000},
        expected_memory={
            0x0EFC: 0x8000,  # PCSEG (segment 0, long form)
            0x0EFE: 0x0210,  # PC offset (return address after CALL)
        },
    ))

    # ---- Test 17: PUSH/POP @RR14 (segmented stack) ----
    # RR14 stack pointer set up by LDA — never hand-code segmented pointers
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0stk=0xF00)
    #   200: 760e 8000 0f00    lda  rr14,0xf00
    #   206: 2100 beef         ld   r0,#0xbeef
    #   20a: 93e0              push @rr14,r0
    #   20c: 2100 0000         ld   r0,#0x0
    #   210: 97e0              pop  r0,@rr14
    tests.append(_tc(
        name='seg_push_pop_seg0',
        mnemonic='PUSH',
        desc='PUSH @RR14, R0 / POP R0, @RR14 (segmented stack)',
        tags=['segmented', 'seg0', 'push', 'pop', 'stack'],
        code=[0x760E, 0x8000, 0x0F00, 0x2100, 0xBEEF,
              0x93E0, 0x2100, 0x0000, 0x97E0],
        regs={0: 0x0000},
    ))

    # ---- Test 17b: PUSHL @RR4, RR6 (long push via segmented register-PAIR pointer) ----
    # Mirrors PCOS calluser.s `pushl @rr4, rr6`: the stack pointer is an arbitrary
    # register pair (not RR14/RR15) and the pushed value is a 32-bit seg:offset.
    # RR4 = seg0:0xF00 (pointer), RR6 = seg0:0x430 (value). PUSHL predecrements RR4
    # by 4 then stores RR6 at the new RR4. Observe the two pushed words.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7604 8000 0f00    lda   rr4,0xf00
    #   206: 7606 8000 0430    lda   rr6,0x430
    #   20c: 9146              pushl @rr4,rr6
    tests.append(_tc(
        name='seg_pushl_ir_rr_seg0',
        mnemonic='PUSHL',
        desc='PUSHL @RR4, RR6 (long push via segmented register-pair pointer)',
        tags=['segmented', 'seg0', 'pushl', 'stack', 'ir_pair'],
        code=[0x7604, 0x8000, 0x0F00,
              0x7606, 0x8000, 0x0430,
              0x9146],
        regs={4: 0x0000, 5: 0x0000, 6: 0x0000, 7: 0x0000},
    ))
    tests[-1].observe_memory = [0x0EFC, 0x0EFE]

    # ---- Test 17c: PUSHL then POPL round-trip via segmented register-PAIR pointer ----
    # Exercises both PUSHL @RR4,RR6 and POPL RR8,@RR4. After the round-trip RR8
    # should equal RR6 and RR4 should return to seg0:0xF00.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7604 8000 0f00    lda   rr4,0xf00
    #   206: 7606 8000 0430    lda   rr6,0x430
    #   20c: 9146              pushl @rr4,rr6
    #   20e: 9548              popl  rr8,@rr4
    tests.append(_tc(
        name='seg_pushl_popl_ir_rr_seg0',
        mnemonic='PUSHL',
        desc='PUSHL @RR4,RR6 then POPL RR8,@RR4 (segmented pair pointer round-trip)',
        tags=['segmented', 'seg0', 'pushl', 'popl', 'stack', 'ir_pair'],
        code=[0x7604, 0x8000, 0x0F00,
              0x7606, 0x8000, 0x0430,
              0x9146, 0x9548],
        regs={4: 0x0000, 5: 0x0000, 6: 0x0000, 7: 0x0000,
              8: 0x0000, 9: 0x0000},
    ))
    tests[-1].observe_memory = [0x0EFC, 0x0EFE]

    # ---- Test 17d: LD word via BX (segmented register-PAIR base + index) ----
    # Mirrors PCOS reloc_type4_word `ld rr2(r7), r6` (STORE) / `ld r6, rr2(r7)`.
    # Base RR2 = seg0:0x400, index R7 = 0x10 -> effective offset 0x410. Store R6
    # (0xBEEF) there, then load it back into R8. NOTE: the segmented assembler
    # requires a register-PAIR base here; the existing seg_cov_161/166 BX tests use
    # a word-register base (-z8002 encoding) and do NOT exercise this form.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7602 8000 0400    lda  rr2,0x400
    #   206: 2107 0010         ld   r7,#0x10
    #   20a: 2106 beef         ld   r6,#0xbeef
    #   20e: 7326 0700         ld   rr2(r7),r6
    #   212: 7128 0700         ld   r8,rr2(r7)
    tests.append(_tc(
        name='seg_ld_bx_store_rr_seg0',
        mnemonic='LD',
        desc='LD rr2(r7),r6 then LD r8,rr2(r7) (segmented pair-base indexed word store/load)',
        tags=['segmented', 'seg0', 'ld', 'bx_pair', 'indexed', 'store'],
        code=[0x7602, 0x8000, 0x0400,
              0x2107, 0x0010,
              0x2106, 0xBEEF,
              0x7326, 0x0700,
              0x7128, 0x0700],
        regs={2: 0x0000, 3: 0x0000, 6: 0x0000, 7: 0x0000, 8: 0x0000},
        memory={SEG0_LONG_ADDR + 0x10: 0x0000},
    ))
    tests[-1].observe_memory = [SEG0_LONG_ADDR + 0x10]

    # ---- Test 17e: LDB byte via BX (segmented register-PAIR base + index) ----
    # Mirrors PCOS reloc_type5_seg `ldb rr2(r7), rh6` (STORE) / `ldb rh6, rr2(r7)`.
    # Base RR2 = seg0:0x400, index R7 = 0x11 (odd lane) -> offset 0x411. Store byte
    # 0xA5 there, then load it back into RH0. mem[0x410] is preloaded so the
    # unaffected (high) byte is observable.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7602 8000 0400    lda  rr2,0x400
    #   206: 2107 0011         ld   r7,#0x11
    #   20a: c6a5              ldb  rh6,#0xa5
    #   20c: 7226 0700         ldb  rr2(r7),rh6
    #   210: 7020 0700         ldb  rh0,rr2(r7)
    tests.append(_tc(
        name='seg_ldb_bx_store_rr_seg0',
        mnemonic='LDB',
        desc='LDB rr2(r7),rh6 then LDB rh0,rr2(r7) (segmented pair-base indexed byte store/load)',
        tags=['segmented', 'seg0', 'ldb', 'bx_pair', 'indexed', 'store', 'byte'],
        code=[0x7602, 0x8000, 0x0400,
              0x2107, 0x0011,
              0xC6A5,
              0x7226, 0x0700,
              0x7020, 0x0700],
        regs={0: 0x0000, 2: 0x0000, 3: 0x0000, 6: 0x0000, 7: 0x0000},
        memory={SEG0_LONG_ADDR + 0x10: 0x1234},
    ))
    tests[-1].observe_memory = [SEG0_LONG_ADDR + 0x10]

    # ---- Test 17f: LDL via BA (segmented register-PAIR base + immediate disp) ----
    # Mirrors PCOS `ldl rr10, rr2(#4)` (opcode 0x35, LDL base+disp). Base RR2 =
    # seg0:0x400, disp #4 -> load the 32-bit value at seg0:0x404 into RR10.
    # NOTE: the only existing 0x35 seg test (seg_cov_239) is LDRL (PC-relative,
    # rs=0); the base-register form (rs!=0) is otherwise uncovered. The
    # seg_cov_218 "ldl_ba" test actually encodes X-mode (0x54) with an odd base.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7602 8000 0400    lda  rr2,0x400
    #   206: 352a 0004         ldl  rr10,rr2(#0x4)
    tests.append(_tc(
        name='seg_ldl_ba_rr_seg0',
        mnemonic='LDL',
        desc='LDL RR10, RR2(#4) (segmented pair-base + immediate displacement)',
        tags=['segmented', 'seg0', 'ldl', 'ba_pair', 'based'],
        code=[0x7602, 0x8000, 0x0400,
              0x352A, 0x0004],
        regs={2: 0x0000, 3: 0x0000, 10: 0x0000, 11: 0x0000},
        memory={SEG0_LONG_ADDR + 4: 0x1234, SEG0_LONG_ADDR + 6: 0x5678},
    ))

    # ---- Test 17g: LDA via BA (segmented register-PAIR base + immediate disp) ----
    # `lda rr8, rr2(#4)` (opcode 0x34, LDA base+disp). Base RR2 = seg0:0x400,
    # disp #4 -> RR8 receives the effective segmented address seg0:0x404 (no
    # memory read). dest(RR8) != base(RR2). NOTE: the only existing 0x34 seg test
    # (seg_cov_175) is LDAR (PC-relative, rs=0); the cov_173 "lda_ba" test is
    # actually opcode 0x76 (indexed). The base-register form is otherwise uncovered.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 7602 8000 0400    lda  rr2,0x400
    #   206: 3428 0004         lda  rr8,rr2(#0x4)
    tests.append(_tc(
        name='seg_lda_ba_rr_seg0',
        mnemonic='LDA',
        desc='LDA RR8, RR2(#4) (segmented pair-base + immediate displacement)',
        tags=['segmented', 'seg0', 'lda', 'ba_pair', 'based'],
        code=[0x7602, 0x8000, 0x0400,
              0x3428, 0x0004],
        regs={2: 0x0000, 3: 0x0000, 8: 0x0000, 9: 0x0000},
    ))

    # ---- Test 17h: LDA BA cross-segment (catches stale-segment hazard) ----
    # `lda rr8, rr4(#4)` must take its SEGMENT from the base RR4, not from
    # whatever segment was last touched. Prime a different segment first with a
    # seg1 indirect read, then LDA a seg0 base: the result must be seg0:0x404.
    #   RR2 = seg1:0x200 (preset), RR4 = seg0:0x400 (preset)
    #   ld  r0,@rr2       -> reads seg1:0x200 (0xCAFE), sets the data segment to 1
    #   lda rr8,rr4(#4)   -> RR8 = seg0:0x404   (NOT seg1:0x404)
    # A soft core that carries the previous segment into the LDA result yields
    # 8100:0404 here instead of 8000:0404; the hard-CPU golden is 8000:0404.
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2120              ld   r0,@rr2
    #   202: 3448 0004         lda  rr8,rr4(#0x4)
    tests.append(_tc(
        name='seg_lda_ba_xseg',
        mnemonic='LDA',
        desc='LDA RR8, RR4(#4) after a seg1 read (segment must come from base, not prior access)',
        tags=['segmented', 'cross_segment', 'lda', 'ba_pair', 'based'],
        code=[0x2120,
              0x3448, 0x0004],
        regs={0: 0x0000,
              2: 0x8100, 3: 0x0200,   # RR2 = seg1:0x200
              4: 0x8000, 5: 0x0400,   # RR4 = seg0:0x400
              8: 0x0000, 9: 0x0000},
        memory={SEG1_Z80_ADDR: 0xCAFE},
    ))

    # ---- Test 18: LDL RR0 from segment 1 (32-bit load) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s1data=seg1:0x200)
    #   200: 5400 8100 0200    ldl  rr0,0x1000200
    tests.append(_tc(
        name='seg_ldl_rr0_seg1',
        mnemonic='LDL',
        desc='LDL RR0, seg1:0x200 (32-bit load cross-segment)',
        tags=['segmented', 'seg1', 'long_word', 'cross_segment'],
        code=[0x5400, 0x8100, 0x0200],
        regs={0: 0x0000, 1: 0x0000},
        memory={SEG1_Z80_ADDR: 0x1234, SEG1_Z80_ADDR + 2: 0x5678},
    ))

    # ---- Test 19: LDA RR2, seg0_data (load address) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 7602 8000 0400    lda  rr2,0x400
    tests.append(_tc(
        name='seg_lda_rr2_seg0',
        mnemonic='LDA',
        desc='LDA RR2, seg0:0x400 (load segmented address)',
        tags=['segmented', 'seg0', 'load_address'],
        code=[0x7602, 0x8000, 0x0400],
        regs={2: 0x0000, 3: 0x0000},
    ))

    # ---- Test 20: ADD R0, seg0_da (arithmetic with DA mode) ----
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200, .s0long=0x400)
    #   200: 4100 8000 0400    add  r0,0x400
    tests.append(_tc(
        name='seg_add_r_da_seg0',
        mnemonic='ADD',
        desc='ADD R0, seg0:0x400 (arithmetic with DA addressing)',
        tags=['segmented', 'seg0', 'arithmetic', 'da_mode'],
        code=[0x4100, 0x8000, 0x0400],
        regs={0: 0x1000},
        memory={SEG0_LONG_ADDR: 0x0234},
    ))

    # ---- Test 21: SC #0 (System Call trap, segmented) ----
    # Sets up PSAP and system stack, executes SC, handler loads R0 marker.
    # Stack frame (4 words pushed): identifier, old FCW, PCSEG, PC offset
    # ASSEMBLER-VERIFIED LISTING (z8k-coff-as -z8001, linked at .text=0x200)
    #   200: 2101 0800           ld   r1,#0x800
    #   204: 7d1d                ldctl psapoff,r1
    #   206: 2101 8000           ld   r1,#0x8000
    #   20a: 7d1c                ldctl psapseg,r1
    #   20c: 760e 8000 0f00      lda  rr14,0x0f00
    #   212: 2100 0000           ld   r0,#0x0
    #   216: 7f00                sc   #0
    #   218: 2100 dead           ld   r0,#0xdead          (should NOT execute)
    #   21c: 5e08 00c0           jp   t,0x00c0            (should NOT reach)
    # Handler at 0x300 (via memory preload):
    #   300: 2100 55aa           ld   r0,#0x55aa
    #   304: 5e08 00c0           jp   t,0x00c0
    # PSA at PSAP+0x18=0x818: reserved(+0), FCW(+2), PCSEG(+4), PC_off(+6)
    tests.append(_tc(
        name='seg_sc_basic',
        mnemonic='SC',
        desc='SC #0: system call trap, verify stack frame',
        tags=['segmented', 'seg0', 'sc', 'trap'],
        code=[0x2101, 0x0800, 0x7D1D, 0x2101, 0x8000, 0x7D1C,
              0x760E, 0x8000, 0x0F00, 0x2100, 0x0000, 0x7F00,
              0x2100, 0xDEAD, 0x5E08, 0x00C0],
        regs={0: 0x0000, 1: 0x0000},
        memory={
            # Handler code at 0x300
            0x0300: 0x2100, 0x0302: 0x55AA,
            0x0304: 0x5E08, 0x0306: 0x00C0,
            # PSA: reserved(+0), FCW(+2), PCSEG(+4), PC_off(+6)
            0x0818: 0x0000, 0x081A: 0xC000,
            0x081C: 0x8000, 0x081E: 0x0300,
        },
        expected_regs={0: 0x55AA, 14: 0x8000, 15: 0x0EF8},
        expected_memory={
            0x0EF8: 0x7F00,  # Identifier (SC instruction word)
            0x0EFA: 0xC000,  # Old FCW
            0x0EFC: 0x8000,  # PCSEG (segment 0, long form)
            0x0EFE: 0x0218,  # PC offset (return address after SC)
        },
    ))

    return tests
