// AUTO-GENERATED by uasm - DO NOT EDIT
// Source: z8000.uasm
//
// Microcode address definitions for use in z8000_cpu.v
// Include this file to avoid hardcoded microcode addresses

`define UADDR_FETCH            11'h00C
`define UADDR_TRAP_ILLEGAL     11'h6DE
`define UADDR_TRAP_PRIV        11'h6EE
`define UADDR_TRAP_SYSCALL     11'h6FE
`define UADDR_INT_ENTRY        11'h70E
