#!/usr/bin/env python3
"""
Convert Intel HEX or raw hex file to Altera MIF (Memory Initialization File) format.

Usage: python gen_mif.py <input.hex> <output.mif> [depth] [width]

Default: 8192 depth (8KB), 8-bit width
"""

import sys
import os

def parse_intel_hex(filename):
    """Parse Intel HEX file format."""
    data = {}
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line.startswith(':'):
                continue

            byte_count = int(line[1:3], 16)
            address = int(line[3:7], 16)
            record_type = int(line[7:9], 16)

            if record_type == 0:  # Data record
                for i in range(byte_count):
                    data[address + i] = int(line[9 + i*2:11 + i*2], 16)
            elif record_type == 1:  # EOF
                break

    return data

def parse_raw_hex(filename):
    """Parse raw hex file (one byte per line or continuous hex)."""
    data = {}
    address = 0

    with open(filename, 'r') as f:
        content = f.read()

    # Try to detect format
    lines = content.strip().split('\n')

    for line in lines:
        line = line.strip()
        if not line or line.startswith('//') or line.startswith('#'):
            continue

        # Handle different formats
        if ' ' in line:
            # Space-separated: "addr: data" or just "data data data"
            parts = line.replace(':', ' ').split()
            for part in parts:
                try:
                    val = int(part, 16)
                    if val <= 255:
                        data[address] = val
                        address += 1
                except ValueError:
                    pass
        else:
            # Continuous hex or one value per line
            try:
                if len(line) == 2:
                    data[address] = int(line, 16)
                    address += 1
                else:
                    # Continuous hex string
                    for i in range(0, len(line), 2):
                        data[address] = int(line[i:i+2], 16)
                        address += 1
            except ValueError:
                pass

    return data

def write_mif(data, filename, depth=8192, width=8):
    """Write MIF file."""
    with open(filename, 'w') as f:
        f.write(f"-- Z80 Firmware Memory Initialization File\n")
        f.write(f"-- Generated by gen_mif.py\n")
        f.write(f"-- Depth: {depth}, Width: {width}\n\n")
        f.write(f"DEPTH = {depth};\n")
        f.write(f"WIDTH = {width};\n")
        f.write(f"ADDRESS_RADIX = HEX;\n")
        f.write(f"DATA_RADIX = HEX;\n\n")
        f.write(f"CONTENT\nBEGIN\n")

        # Find contiguous ranges for compact output
        addresses = sorted(data.keys())

        if not addresses:
            # Empty - fill with zeros
            f.write(f"[0..{depth-1}] : 00;\n")
        else:
            last_written = -1

            for addr in addresses:
                if addr >= depth:
                    break

                # Fill gap with zeros if needed
                if addr > last_written + 1:
                    gap_start = last_written + 1
                    gap_end = addr - 1
                    if gap_start == gap_end:
                        f.write(f"{gap_start:04X} : 00;\n")
                    else:
                        f.write(f"[{gap_start:04X}..{gap_end:04X}] : 00;\n")

                f.write(f"{addr:04X} : {data[addr]:02X};\n")
                last_written = addr

            # Fill remaining with zeros
            if last_written < depth - 1:
                f.write(f"[{last_written + 1:04X}..{depth - 1:04X}] : 00;\n")

        f.write(f"END;\n")

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <input.hex> <output.mif> [depth] [width]")
        print(f"Default: depth=8192, width=8")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]
    depth = int(sys.argv[3]) if len(sys.argv) > 3 else 8192
    width = int(sys.argv[4]) if len(sys.argv) > 4 else 8

    if not os.path.exists(input_file):
        print(f"Error: Input file '{input_file}' not found")
        sys.exit(1)

    # Try Intel HEX first, fall back to raw hex
    try:
        with open(input_file, 'r') as f:
            first_line = f.readline().strip()

        if first_line.startswith(':'):
            print(f"Parsing Intel HEX format...")
            data = parse_intel_hex(input_file)
        else:
            print(f"Parsing raw hex format...")
            data = parse_raw_hex(input_file)
    except Exception as e:
        print(f"Error parsing input file: {e}")
        sys.exit(1)

    print(f"Read {len(data)} bytes from {input_file}")

    write_mif(data, output_file, depth, width)
    print(f"Wrote MIF file: {output_file} (depth={depth}, width={width})")

if __name__ == "__main__":
    main()
