#!/usr/bin/env python3
"""
Generate minimal Z80 test firmware for UART echo.
This is a hand-assembled minimal program to test serial communication.

Memory map:
  0x0000-0x1FFF: RAM (code runs from here)

I/O ports:
  0x00: UART data (R/W)
  0x01: UART status (bit0=tx_ready, bit1=rx_valid)

Program: Echo characters back with ">" prefix
"""

import sys

# Z80 opcodes (hand-assembled)
firmware = []

def emit(byte):
    firmware.append(byte & 0xFF)

def emit_word(word):
    emit(word & 0xFF)
    emit((word >> 8) & 0xFF)

# org 0x0000
# start:
#     ld sp, 0x2000       ; 31 00 20 - Initialize stack
emit(0x31); emit_word(0x2000)

# main_loop:                ; Address 0x0003
#     ; Print ">" prompt
#     ld a, '>'           ; 3E 3E
emit(0x3E); emit(0x3E)
#     call put_char       ; CD xx xx (address TBD)
emit(0xCD); emit_word(0x0020)  # put_char at 0x0020

#     ; Wait for and get character
#     call get_char       ; CD xx xx (address TBD)
emit(0xCD); emit_word(0x0030)  # get_char at 0x0030

#     ; Echo character back
#     call put_char       ; CD xx xx
emit(0xCD); emit_word(0x0020)

#     ; Print newline
#     ld a, 0x0D          ; CR
emit(0x3E); emit(0x0D)
#     call put_char
emit(0xCD); emit_word(0x0020)
#     ld a, 0x0A          ; LF
emit(0x3E); emit(0x0A)
#     call put_char
emit(0xCD); emit_word(0x0020)

#     jp main_loop        ; C3 03 00
emit(0xC3); emit_word(0x0003)

# Pad to put_char at 0x0020
while len(firmware) < 0x0020:
    emit(0x00)  # NOP padding

# put_char: (at 0x0020)
#     ; Wait for TX ready (bit 0 of port 0x01)
# wait_tx:
#     in a, (0x01)        ; DB 01
emit(0xDB); emit(0x01)
#     bit 0, a            ; CB 47
emit(0xCB); emit(0x47)
#     jr z, wait_tx       ; 28 FA (-6)
emit(0x28); emit(0xFA)
#     ; Send character (A register has char to send)
#     ; But we need to save A first... let's use different approach
# Actually, the put_char receives char in A, but we check status first
# which destroys A. Let's fix this:

# Restart put_char properly at 0x0020
firmware = firmware[:0x0020]

# put_char: (at 0x0020) - char in A
#     push af             ; F5 - save char
emit(0xF5)
# wait_tx:                ; 0x0021
#     in a, (0x01)        ; DB 01
emit(0xDB); emit(0x01)
#     and 0x01            ; E6 01 - check TX ready
emit(0xE6); emit(0x01)
#     jr z, wait_tx       ; 28 FA (-6 -> back to 0x0021)
emit(0x28); emit(0xFB)
#     pop af              ; F1 - restore char
emit(0xF1)
#     out (0x00), a       ; D3 00 - send char
emit(0xD3); emit(0x00)
#     ret                 ; C9
emit(0xC9)

# Pad to get_char at 0x0030
while len(firmware) < 0x0030:
    emit(0x00)

# get_char: (at 0x0030) - returns char in A
# wait_rx:                ; 0x0030
#     in a, (0x01)        ; DB 01
emit(0xDB); emit(0x01)
#     and 0x02            ; E6 02 - check RX valid (bit 1)
emit(0xE6); emit(0x02)
#     jr z, wait_rx       ; 28 FA (-6 -> back to 0x0030)
emit(0x28); emit(0xFA)
#     in a, (0x00)        ; DB 00 - read char
emit(0xDB); emit(0x00)
#     ret                 ; C9
emit(0xC9)

# Pad to 256 bytes minimum
while len(firmware) < 256:
    emit(0x00)

def write_hex(filename):
    """Write raw hex file (one byte per line)."""
    with open(filename, 'w') as f:
        for b in firmware:
            f.write(f"{b:02X}\n")
    print(f"Wrote {filename}: {len(firmware)} bytes")

def write_mif(filename, depth=8192):
    """Write Altera MIF file."""
    with open(filename, 'w') as f:
        f.write("-- Minimal Z80 UART Echo Firmware\n")
        f.write("-- Generated by z80_fw_minimal.py\n\n")
        f.write(f"DEPTH = {depth};\n")
        f.write("WIDTH = 8;\n")
        f.write("ADDRESS_RADIX = HEX;\n")
        f.write("DATA_RADIX = HEX;\n\n")
        f.write("CONTENT\nBEGIN\n")

        # Write firmware bytes
        for addr, byte in enumerate(firmware):
            f.write(f"{addr:04X} : {byte:02X};\n")

        # Fill rest with zeros
        if len(firmware) < depth:
            f.write(f"[{len(firmware):04X}..{depth-1:04X}] : 00;\n")

        f.write("END;\n")
    print(f"Wrote {filename}: {len(firmware)} bytes of code, {depth} total depth")

def write_bin(filename):
    """Write binary file."""
    with open(filename, 'wb') as f:
        f.write(bytes(firmware))
    print(f"Wrote {filename}: {len(firmware)} bytes")

if __name__ == "__main__":
    print(f"Firmware size: {len(firmware)} bytes")
    print(f"Entry point: 0x0000")
    print(f"put_char: 0x0020")
    print(f"get_char: 0x0030")
    print()

    # Write all formats
    write_hex("z80_fw.hex")
    write_mif("z80_fw.mif")
    write_bin("z80_fw.bin")

    # Disassembly for verification
    print("\nDisassembly:")
    print("0000: 31 00 20     LD SP, 2000h")
    print("0003: 3E 3E        LD A, '>'")
    print("0005: CD 20 00     CALL 0020h (put_char)")
    print("0008: CD 30 00     CALL 0030h (get_char)")
    print("000B: CD 20 00     CALL 0020h (put_char)")
    print("000E: 3E 0D        LD A, 0Dh (CR)")
    print("0010: CD 20 00     CALL 0020h")
    print("0013: 3E 0A        LD A, 0Ah (LF)")
    print("0015: CD 20 00     CALL 0020h")
    print("0018: C3 03 00     JP 0003h (main_loop)")
    print()
    print("0020: F5           PUSH AF (put_char)")
    print("0021: DB 01        IN A, (01h)")
    print("0023: E6 01        AND 01h")
    print("0025: 28 FB        JR Z, 0021h")
    print("0027: F1           POP AF")
    print("0028: D3 00        OUT (00h), A")
    print("002A: C9           RET")
    print()
    print("0030: DB 01        IN A, (01h) (get_char)")
    print("0032: E6 02        AND 02h")
    print("0034: 28 FA        JR Z, 0030h")
    print("0036: DB 00        IN A, (00h)")
    print("0038: C9           RET")
