// True Dual-Port 16-bit RAM using Gowin DPB IP
// Port A: Z80 harness access (load/read test code)
// Port B: Z8000 CPU access (fetch/execute)
// Both ports can read and write independently.
//
// 8K bytes (4K words) with byte write enables.
// Uses 2x Gowin_DPB (4Kx8 true dual-port BRAM).

module ram16 (
    // Port A (Z80 harness)
    input         clka,
    input         wea_hi,      // Write enable high byte
    input         wea_lo,      // Write enable low byte
    input  [12:0] addra,       // 13-bit BYTE address
    input  [15:0] dina,
    output [15:0] douta,
    // Port B (Z8000 CPU)
    input         clkb,
    input         web_hi,      // Write enable high byte
    input         web_lo,      // Write enable low byte
    input  [12:0] addrb,       // 13-bit BYTE address
    input  [15:0] dinb,
    output [15:0] doutb
);

    wire [7:0] douta_hi, douta_lo;
    wire [7:0] doutb_hi, doutb_lo;

    // High byte (D15-D8)
    Gowin_DPB ram_hi (
        // Port A
        .clka   (clka),
        .ocea   (1'b1),
        .cea    (1'b1),
        .reseta (1'b0),
        .wrea   (wea_hi),
        .ada    (addra[12:1]),
        .dina   (dina[15:8]),
        .douta  (douta_hi),
        // Port B
        .clkb   (clkb),
        .oceb   (1'b1),
        .ceb    (1'b1),
        .resetb (1'b0),
        .wreb   (web_hi),
        .adb    (addrb[12:1]),
        .dinb   (dinb[15:8]),
        .doutb  (doutb_hi)
    );

    // Low byte (D7-D0)
    Gowin_DPB ram_lo (
        // Port A
        .clka   (clka),
        .ocea   (1'b1),
        .cea    (1'b1),
        .reseta (1'b0),
        .wrea   (wea_lo),
        .ada    (addra[12:1]),
        .dina   (dina[7:0]),
        .douta  (douta_lo),
        // Port B
        .clkb   (clkb),
        .oceb   (1'b1),
        .ceb    (1'b1),
        .resetb (1'b0),
        .wreb   (web_lo),
        .adb    (addrb[12:1]),
        .dinb   (dinb[7:0]),
        .doutb  (doutb_lo)
    );

    assign douta = {douta_hi, douta_lo};
    assign doutb = {doutb_hi, doutb_lo};

    // Bootstrap initialization (generated by scripts/gen_bram_init.py)
    `include "bram_init.vh"

endmodule
