// AUTO-GENERATED by uasm - DO NOT EDIT
// Source: z8000.uasm
//
// Microcode address definitions for use in z8000_cpu.v
// Include this file to avoid hardcoded microcode addresses

`define UADDR_FETCH            12'h00C
`define UADDR_TRAP_ILLEGAL     12'h854
`define UADDR_TRAP_PRIV        12'h864
`define UADDR_TRAP_SYSCALL     12'h874
`define UADDR_INT_ENTRY        12'h884
